export const Authors = [
  {
    firstName: "Kate",
    lastName: "Harris",
    website: "https://www.kateharris.co.uk/",
    socialMedia: {
      instagram: "https://www.instagram.com/katelifecoach",
      facebook: "https://facebook.com/kate.harris.12979",
      twitter: "https://twitter.com/hometoyourheart",
    },
    umbrellaGenre: ["nonfiction"],
    subGenre: ["Memoir", "Poetry", "Self-help", "Art"],
    bio: [
      `Kate is an author, artist and life coach in Devon, England. Inspired by nature, she has created a blend of memoir, poetry and paintings to reveal the essence of freedom, hope and joy within the evolution of our lives. A glimmer of sun on a dull day to light the way forward for you to fly home to your heart.`,
      `Kate was an Occupational Therapist for many years in the mental health service, where creativity was the door to recovery for many people.`,
    ],
  },
  {
    firstName: "Olivia",
    lastName: "Raymond",
    website: "https://www.oliviaraymond.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/authoroliviaraymond/",
    },
    umbrellaGenre: ["thriller", "drama"],
    subGenre: ["Mystery"],
    bio: [
      `Olivia Raymond was born in the small town of Greensburg, Indiana, best known for the mulberry tree growing out of its courthouse tower. Olivia's family moved to Indianapolis when she was just seven years old, but by then, the small-town life had already taken root and made its lasting impression. Olivia had several careers before becoming a successful business entrepreneur. Her various life and career adventures provided her with many experiences that help shape her stories. She now resides in a small town with her family and sweet furry companion, Mr. Ralf, where she enjoys her time as a writer and volunteer for the arts in her community.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Whitney",
    lastName: "Cubbison",
    email: "whitneyc2@hotmail.com",
    website: "https://www.datingdisasters.paris/",
    umbrellaGenre: ["romance"],
    subGenre: ["Romcom"],
    socialMedia: {
      instagram: "https://www.instagram.com/whitneycubbisonwrites/",
      facebook: "https://www.facebook.com/profile.php?id=100087468011635",
      twitter: null,
      tiktok: "https://www.tiktok.com/@whitneycubbisonwrites",
      goodreads:
        "https://www.goodreads.com/author/show/23134149.Whitney_Cubbison",
      mastodon: null,
      amazonBio: "https://www.amazon.com/stores/author/B0BMB8RG5D",
      threads: null,
      bookbub: null,
    },
    bio: [
      "Whitney Cubbison is a dual American & French citizen living in Paris since 2009. She grew up in Texas and California and graduated from UCLA with a degree in French. She started her career in Communications working for high-tech PR agencies in San Francisco and eventually joined Microsoft where she worked for sixteen years, thirteen of which from the Paris office. During that time, she held various international roles that encompassed public relations, employee communications, executive speechwriting, and social media.",
      "She earned her French citizenship in early 2022 and left Microsoft in the summer of that year to focus on completing her first novel, Will There Be Wine? The story, while fiction, is deeply inspired by Whitney’s own experiences as an ex-pat divorcée living in Paris and trying to navigate the cultural minefield of dating in a foreign country. It was released on January 16, 2023.",
      "When she’s not writing, Whitney can be found sitting in Parisian cafés and restaurants with her friends, drinking wine.",
    ],
  },
  {
    firstName: "Finley K.",
    lastName: "James",
    email: "finley.k.james29@gmail.com",
    website: "https://finleykjames.com/",
    umbrellaGenre: ["romance", "drama"],
    subGenre: ["Contemporary"],
    socialMedia: {
      instagram: "https://instagram.com/finleykjamesauthor",
      facebook: "https://facebook.com/finleykjamesauthor",
      twitter: null,
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: "https://threads.net/@finleykjamesauthor",
      bookbub: null,
    },
    bio: [
      "Hi! I’m Finley. I’m an 80-year-old woman in the body of a not-so-80-years-old woman. I write contemporary romance full of love, drama, and character growth. I live in the southern Midwest with my husband, our three kids, and our cats. I spend most of my time dreaming of the next project and word-vomiting onto pages only to delete them later. ",
    ],
    isVerified: true,
  },
  {
    firstName: "Nick",
    lastName: "Snape",
    email: "nick@nicksnape.com",
    website: "https://www.nicksnape.com/",
    umbrellaGenre: ["scifi"],
    subGenre: ["Horror"],
    socialMedia: {
      instagram: "https://www.instagram.com/nick.snape.author/",
      facebook: null,
      twitter: "https://www.twitter.com/SnapeNick",
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: null,
      bookbub: null,
    },
    bio: [
      "Nick Snape has been steeped in Science Fiction and Fantasy since his friends first dragged him from his schoolwork and stuck a book under his nose. Lost to the world of imagination he became a teacher by accident though he thoroughly enjoyed developing the joy of reading and writing in his pupils. Having retired after thirty years he thought it was high time to practice what he preached.",
    ],
  },
  {
    firstName: "Jamie",
    lastName: "Payne",
    email: "jamie@biggledink.co.uk",
    website: "https://www.biggledink.co.uk/",
    umbrellaGenre: ["childrens"],
    subGenre: ["Picture Books", "Early Readers"],
    socialMedia: {
      instagram: "https://www.instagram.com/biggle.dink/",
      facebook: "https://www.facebook.com/biggledink",
      twitter: "https://twitter.com/biggledink",
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: null,
      bookbub: null,
    },
    bio: [
      "Biggle-Dink is a curious child who is fascinated by the seemingly ordinary world around them. With new discoveries and interests come new emotions and feelings. Join Biggle-Dink and their friends as we explore some of these new things together and discover how they might make us feel.",
      "Created by children's author Jamie Payne, Biggle-Dink is the title character of a collection of illustrated books that focus on different feelings and emotions that children can experience. The stories are written for younger children, with a broad targeted age range of 2 to 8 years old. They can be read to your little ones and also enjoyed independently by those older.",
    ],
    isVerified: true,
  },
  {
    firstName: "Dominique",
    lastName: "Davis",
    email: "contact@dominique-davis.com",
    website: "https://www.dominique-davis.com/",
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "New Adult"],
    socialMedia: {
      instagram: "https://instagram.com/ddaviswrites",
      facebook: null,
      twitter: "https://twitter.com/ddaviswrites",
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: null,
      bookbub: null,
    },
    bio: [
      "A 20-year-old writer who writes about pop culture and unhinged women falling in love (many of whom are sapphic).",
    ],
  },
  {
    firstName: "S J",
    lastName: "Sparkle",
    email: "sjsparkle86@gmail.com",
    website: "https://www.stefansparkleauthor.com/",
    umbrellaGenre: ["romance"],
    subGenre: ["Regency Heartwarming"],
    socialMedia: {
      instagram: "http://instagram.com/sjsparkleauthor",
      facebook: null,
      twitter: null,
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: "https://www.threads.net/@sjsparkleauthor",
      bookbub: null,
    },
    bio: [
      "S J Sparkle is true to his name, which was given to him when he got married. It's not a pseudonym it's a way of life! ",
      "He writes heartwarming cozy regency romance novels that are tastefully spicy, research heavy, and have just enough going on to keep you turning the page.",
      "When he's not writing he's with his wife and cats or being a sparkly presence on Threads.",
    ],
  },
  {
    firstName: "Anne",
    lastName: "Brooke",
    email: "annebrooke1993@gmail.com",
    website: "http://www.annebrooke.com/",
    umbrellaGenre: ["romance", "fantasy", "thriller", "comedy"],
    subGenre: ["Women's Fiction", "Gay Fiction", "Paranormal Fiction"],
    socialMedia: {
      instagram: "https://www.instagram.com/annebrooke1993/",
      facebook: "https://www.facebook.com/annebrookebooks/",
      twitter: "https://twitter.com/AnneBrookeBooks",
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: "https://www.threads.net/@annebrooke1993",
      bookbub: null,
    },
    bio: [
      "Anne Brooke lives in the UK and has been writing fiction for over twenty years. In the past she has been shortlisted for the Harry Bowling Prize (for novels set in London) and longlisted for the Betty Bolingbroke-Kent Novel Award. When not writing, she enjoys gardening and Pilates, and would love to be able to dance.",
    ],
  },
  {
    firstName: "Autumn",
    lastName: "Kaufer",
    email: "Arkauferauthor@gmail.com",
    website: "https://www.arkauferauthor.com/",
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["Romantic Fantasy", "Paranormal Romance", "YA Fantasy"],
    socialMedia: {
      instagram: "https://www.instagram.com/authorarkaufer/",
      facebook: null,
      twitter: "https://twitter.com/AutumnK2022",
      tiktok: "https://tiktok.com/@arkauferauthor",
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: null,
      bookbub: null,
    },
    bio: [
      "A.R. Kaufer has dreamed of becoming a published author for as long as she can remember. She lives in Indiana with her wonderful husband and furbabies. When she's not reading or writing, she enjoys playing video games, watching movies, and going for walks in the woods around her home. She is currently working on an eight book fantasy series, with the first book, Courting Fate, available now.",
    ],
  },
  {
    firstName: "Melina",
    lastName: "Druga",
    email: "melinadruga@outlook.com",
    website: "http://www.melinadruga.com/",
    umbrellaGenre: ["romance", "historicalfiction", "nonfiction"],
    subGenre: ["Rock Star Fiction", "Women's Fiction", "History"],
    socialMedia: {
      instagram: "https://www.instagram.com/melinadruga/",
      facebook: "https://www.facebook.com/MelinaDruga",
      twitter: null,
      tiktok: null,
      goodreads: "https://www.goodreads.com/MelinaDruga",
      mastodon: null,
      amazonBio: "https://www.amazon.com/Melina-Druga/e/B00FSFCJOW",
      threads: null,
      bookbub: "https://www.bookbub.com/profile/melina-druga",
    },
    bio: [
      "Rumor has it that Melina Druga came out of her mother’s womb with a pen in her hand.  While we can neither confirm or deny this, you could say she was destined to become a writer.",
      "Melina was so young when she began writing that she can’t remember exactly when the urge began.  She does remember, however, her first novel – an historical fiction story about two sisters living in an Ohio canal town in the 1840s – that she wrote at age 10.",
      "Music keeps Melina sane, and it has gotten to the point that she cannot write without it.  It keeps her awake, alert, motivated and productive.  Music has even inspired her fiction.  And not just The Rock Star’s Wife series.  The My Chemical Romance song “Mama” was the inspiration for her historical fiction novel Angel of Mercy.",
      "Melina lives in the Midwest with her husband, daughter, black cat, books and CD collection.",
    ],
  },
  {
    firstName: "Deborah",
    lastName: "Fox",
    email: "debmac730@gmail.com",
    website: null,
    umbrellaGenre: ["thriller", "horror"],
    subGenre: ["Mystery"],
    socialMedia: {
      instagram: "https://www.instagram.com/deborah9553/",
      facebook: "https://www.facebook.com/deborah.fox.127",
      twitter: "https://twitter.com/debmac730",
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: null,
      bookbub: null,
    },
    bio: [
      "I am 50 years old and live in Doncaster a city in the north of England. When not writing I work for a large electrical distribution company in a busy returns department. My hobbies include gardening, walking, dogs, cinema / theatre and promoting my book Second Hand Rose. This is my first book and it was written and inspired by my dog Jake who sadly passed away so I made him one of the main characters of the story which I then wrote to help with the grieving process.",
    ],
  },
];