export const Authors = [
  {
    firstName: "Test1",
    lastName: "Harris",
    email: "test1@email.com",
    website: "https://www.kateharris.co.uk/",
    socialMedia: {
      instagram: "https://www.instagram.com/katelifecoach",
      facebook: "https://facebook.com/kate.harris.12979",
      twitter: "https://twitter.com/hometoyourheart",
    },
    umbrellaGenre: ["nonfiction"],
    subGenre: ["Memoir", "Poetry", "Self-help", "Art"],
    bio: [
      `Kate is an author, artist and life coach in Devon, England. Inspired by nature, she has created a blend of memoir, poetry and paintings to reveal the essence of freedom, hope and joy within the evolution of our lives. A glimmer of sun on a dull day to light the way forward for you to fly home to your heart.`,
      `Kate was an Occupational Therapist for many years in the mental health service, where creativity was the door to recovery for many people.`,
    ],
  },
  {
    firstName: "Test2",
    lastName: "Raymond",
    email:"test2@email.com",
    website: "https://www.oliviaraymond.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/authoroliviaraymond/",
    },
    umbrellaGenre: ["thriller", "drama"],
    subGenre: ["Mystery"],
    bio: [
      `Olivia Raymond was born in the small town of Greensburg, Indiana, best known for the mulberry tree growing out of its courthouse tower. Olivia's family moved to Indianapolis when she was just seven years old, but by then, the small-town life had already taken root and made its lasting impression. Olivia had several careers before becoming a successful business entrepreneur. Her various life and career adventures provided her with many experiences that help shape her stories. She now resides in a small town with her family and sweet furry companion, Mr. Ralf, where she enjoys her time as a writer and volunteer for the arts in her community.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Test3",
    lastName: "Cubbison",
    email: "test3@email.com",
    website: "https://www.datingdisasters.paris/",
    umbrellaGenre: ["romance"],
    subGenre: ["Romcom"],
    socialMedia: {
      instagram: "https://www.instagram.com/whitneycubbisonwrites/",
      facebook: "https://www.facebook.com/profile.php?id=100087468011635",
      twitter: null,
      tiktok: "https://www.tiktok.com/@whitneycubbisonwrites",
      goodreads:
        "https://www.goodreads.com/author/show/23134149.Whitney_Cubbison",
      mastodon: null,
      amazonBio: "https://www.amazon.com/stores/author/B0BMB8RG5D",
      threads: null,
      bookbub: null,
    },
    bio: [
      "Whitney Cubbison is a dual American & French citizen living in Paris since 2009. She grew up in Texas and California and graduated from UCLA with a degree in French. She started her career in Communications working for high-tech PR agencies in San Francisco and eventually joined Microsoft where she worked for sixteen years, thirteen of which from the Paris office. During that time, she held various international roles that encompassed public relations, employee communications, executive speechwriting, and social media.",
      "She earned her French citizenship in early 2022 and left Microsoft in the summer of that year to focus on completing her first novel, Will There Be Wine? The story, while fiction, is deeply inspired by Whitney’s own experiences as an ex-pat divorcée living in Paris and trying to navigate the cultural minefield of dating in a foreign country. It was released on January 16, 2023.",
      "When she’s not writing, Whitney can be found sitting in Parisian cafés and restaurants with her friends, drinking wine.",
    ],
  },
  {
    firstName: "Test4",
    lastName: "James",
    email: "test4@email.com",
    website: "https://finleykjames.com/",
    umbrellaGenre: ["romance", "drama"],
    subGenre: ["Contemporary"],
    socialMedia: {
      instagram: "https://instagram.com/finleykjamesauthor",
      facebook: "https://facebook.com/finleykjamesauthor",
      twitter: null,
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: "https://threads.net/@finleykjamesauthor",
      bookbub: null,
    },
    bio: [
      "Hi! I’m Finley. I’m an 80-year-old woman in the body of a not-so-80-years-old woman. I write contemporary romance full of love, drama, and character growth. I live in the southern Midwest with my husband, our three kids, and our cats. I spend most of my time dreaming of the next project and word-vomiting onto pages only to delete them later. ",
    ],
    isVerified: true,
  },
  {
    firstName: "Test5",
    lastName: "Snape",
    email: "test5@email.com",
    website: "https://www.nicksnape.com/",
    umbrellaGenre: ["scifi"],
    subGenre: ["Horror"],
    socialMedia: {
      instagram: "https://www.instagram.com/nick.snape.author/",
      facebook: null,
      twitter: "https://www.twitter.com/SnapeNick",
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: null,
      bookbub: null,
    },
    bio: [
      "Nick Snape has been steeped in Science Fiction and Fantasy since his friends first dragged him from his schoolwork and stuck a book under his nose. Lost to the world of imagination he became a teacher by accident though he thoroughly enjoyed developing the joy of reading and writing in his pupils. Having retired after thirty years he thought it was high time to practice what he preached.",
    ],
  },
];