export const Authors = [
  {
    firstName: "T M",
    lastName: "Rowe",
    email: "toni-maree@hotmail.com",
    website: "http://www.tmrowe.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/tonimaree.rowe/",
      twitter: "https://twitter.com/tmrowe70",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Historical Fantasy"],
    bio: [
      `In the time BC (Before Children) Toni-maree was a fair to middling archaeologist and now she is a fair to middling writer who loves to write about the past often with a fantasy twist. Her love of storytelling, myths, legends and fantasy all play a part in her novels – ‘The Adventures of Sarah Tremayne’. When she is not writing you can find her volunteering in the archaeology department of the Auckland Museum or with the New Zealand Archaeological Association as part of their Archaeology Week events. Her other passions include beachcombing and long dog walks in addition to her side hustle of creating art from her beachcombed finds…oh and then there is the whole mother and wife shenanigans!`,
    ],
    isVerified: true,
  },
  {
    firstName: "Kimberly",
    lastName: "Ann",
    email: "kimberlyannromance@gmail.com",
    website: "https://www.kimberlyannauthor.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/KimberlyAnnAuth/",
      instagram: "https://www.instagram.com/kimberlyannbooks/",
      tiktok: "https://www.tiktok.com/@kimberlyannauth",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Small Town", "Contemporary"],
    bio: [
      `Kimberly Ann lives in BC, Canada with her husband, two children and ridiculously cute German Shepherd. When she’s not dreaming of stories, she homeschools her two children as they explore the world together, reads anything she can get her hands on, and drinks a lot of coffee.`,
      `Growing up with her head lost in a book, it was no surprise when she picked up a pen, or her laptop, to write her own. Kimberly Ann’s stories are based on the world around her as she brings her imagination to life with stories of small towns, swoon-worthy men, and the women that keep them on their toes.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Lily",
    lastName: "Lawson",
    email: "lilylawsonwrites@gmail.com",
    website: "https://www.lilyswritinglife.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/poeticrainbow9/",
      twitter: "https://twitter.com/lifelovelily22",
    },
    umbrellaGenre: ["childrens"],
    subGenre: ["Poetry"],
    bio: [
      `Lily Lawson is a poet, children’s and short story writer living in the UK. In addition to her books, she has published poetry, short stories, and creative non-fiction in anthologies and online.`,
      `Find out about Lily and read more of her work on her website: lilyswritinglife.com.  Subscribers to her newsletter, Life with Lily, are the first to hear all her writing news.`,
    ],
    isVerified: true,
  },
  {
    firstName: "M.D.",
    lastName: "LaBelle",
    email: "m.d.labelle0@gmail.com",
    website: "https://www.mdlabelle.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/m.d.labelle/",
      facebook: "https://www.facebook.com/profile.php?id=100062142582314",
      tiktok: "https://www.tiktok.com/@m.d.labelle",
    },
    umbrellaGenre: ["romance", "horror", "childrens"],
    subGenre: [
      "Erotica",
      "YA",
      "Children's Horror",
      "Dark Romance",
      "Fantasy Romance",
      "Billionaire Romance",
      "CEO Romance",
      "Small Town",
      "Age Gap",
      "Paranormal Romance",
      "Psychological Thriller",
      "YA Horror",
      "Rom Com",
    ],
    bio: [
      `M.D. LaBelle is an international award-winning, bestselling multi genre author from Michigan.  She lives in Mount Pleasant, Michigan with 4 of her 6 children and her loving husband.  While she spends most of her time writing, she is also a violinist and has a degree in Art from Central Michigan University.  At the age of 12, she won the Young Author's award for a horror story and now after picking up her pen again, she has won two international competitions in just a few months' time of each other.  Now after publishing 43 books, she not only has her own bookstore, and website but has her works in over 200 paid web novel platforms and on most online bookstores.  Readers often say that while reading her books, "they feel like they are in a movie" because it is so descriptive.  While another reader has even said that they prefer reading her novels to watching Netflix.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Stephanie M.",
    lastName: "Matthews",
    email: "stephanie.matthews@msn.com",
    website: "https://stephaniemmatthews.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/StephanieM.Matthews/",
      facebook: "https://www.facebook.com/StephanieMMatthews/",
      twitter: "https://twitter.com/@smm_author/",
      amazonBio: "https://www.amazon.ca/stores/author/B075JP563N",
      bookbub: "https://www.bookbub.com/profile/stephanie-m-matthews",
    },
    umbrellaGenre: ["thriller", "horror"],
    subGenre: ["Supernatural"],
    bio: [
      `Having been raised as an East Coast girl in Nova Scotia, Stephanie Matthews has spent time living in Newfoundland, Oklahoma, and Italy. She has currently settled in Ontario working for a non-profit organization and writing in her spare time.`,
      `Stephanie’s love of writing came at an early age, drafting her first “real story” in Grade 2. This love of writing has continued throughout her life, and she’s found a home in telling thriller stories that challenge people to see the world with different eyes.`,
      `When not writing, or working, Stephanie enjoys training for obstacle course races, playing hockey badly, and fueling her passion for Ancient Rome.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Julie",
    lastName: "Embleton",
    email: "julie@julieembleton.com",
    website: "https://www.julieembleton.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/julieembletonauthor/",
      tiktok: "https://www.tiktok.com/@julieembletonauthor",
      amazonBio:
        "https://www.amazon.co.uk/stores/Julie-Embleton/author/B079KS86YL",
      bookbub: "https://www.bookbub.com/authors/julie-embleton",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: [
      "Shifter and Vampire Romance",
      "Epic Fantasy",
      "Dystopian Romance",
    ],
    bio: [
      `Julie Embleton is a paranormal fantasy author from Dublin, Ireland. She writes tenacious, kick-ass females who can rescue themselves, thanks very much, gutsy heroes with tender hearts, and heinous villains who thrive on chaos. Her stories weave suspense, romance, and magick, mostly with happy endings, but she does enjoy leaving her readers hanging with the occasional cliffhanger. Julie lives by the shores of the moody Irish Sea, and when not writing, can be found with her second great love; tarot. Her Me-Time typically includes reading, enjoying the outdoors, or watching Turkish soap operas.`,
      `Want to be the first to hear about new releases, giveaways, and exclusive sneak peeks? Sign up to Julie’s newsletter by visiting www.julieembleton.com`,
    ],
    isVerified: true,
  },
  {
    firstName: "Angela",
    lastName: "Cairns",
    email: "angelacairnsauthor@gmail.com",
    website: "https://www.angelacairnsauthor.co.uk/",
    socialMedia: {
      facebook: "https://www.facebook.com/angelacairnsauthor",
      instagram: "https://www.instagram.com/angelacairnsauthor/",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "Historical"],
    bio: [
      `Hi, I'm Angela Cairns and I write enthralling romantic fiction, historical and contemporary with heart, soul and courage.`,
      `In my books you will find resilient, relatable heroines with warm hearts who are trying to do the next right thing, despite difficult circumstances.`,
      `My books are for the stickers and fighters who get knocked down and get right back up again, bruised but not broken. For people who love people and life in all its messy glory. The carers and romantics at heart who dream of real love and happy endings.`,
      `Those who know they have more to give.`,
      `They are for those who reflect on what is in their heart, long to speak their truth, and who know the life they seek is out there.`,
      `If you believe in friends, found-family, love and the joy that peace and fulfilment brings. If you want that connection.`,
      `Pick up my books today.`,
      `Angela`,
      `Author, Writing Coach, Broadcaster, Physiotherapist, Holistic Therapist, Wife, Mum, Owned by Gordon Setters, Believer in Better`,
    ],
    isVerified: true,
  },
  {
    firstName: "Nannette",
    lastName: "Kreitzman",
    email: "nettshorts@gmail.com",
    website: null,
    socialMedia: {
      instagram: "https://www.instagram.com/netts_shorts/",
      goodreads:
        "https://www.goodreads.com/author/show/18633215.Nannette_Kreitzman",
      amazonBio:
        "https://www.amazon.com/stores/Nannette-Kreitzman/author/B07TTXPSPB?ref=dbs_a_mng_awm_scns_share&isDramIntegrated=true&shoppingPortalEnabled=true",
    },
    umbrellaGenre: [
      "romance",
      "fantasy",
      "scifi",
      "drama",
      "western",
      "thriller",
      "horror",
      "historicalfiction",
    ],
    subGenre: ["Short Stories", "Anthologies"],
    bio: [
      `I’m a retired stay at home mom and happy empty nester. I spend my morning walks dreaming up short story ideas but, despite my carefully laid plans, my characters always manage to change things up! I’ve learned to pay attention to them though, they’re usually right.`,
    ],
  },
  {
    firstName: "Laura",
    lastName: "Lyndhurst",
    email: "lyndhurstlaura505@gmail.com",
    website: null,
    socialMedia: {
      instagram: "https://www.instagram.com/lyndhurstlaura/",
      facebook: "https://www.facebook.com/lauralyndhurstauthor",
      goodreads:
        "https://www.goodreads.com/author/show/20336562.Laura_Lyndhurst",
    },
    umbrellaGenre: ["thriller"],
    subGenre: [
      "Literary Fiction",
      "Psychological Suspense Thrillers",
      "Social Commentrary Free Verse",
    ],
    bio: [
      `I was born and grew up in North London, England, but was unable to attend university when young due to family financial circumstances. Instead, I worked at various occupations, including dental nurse, laboratory assistant and shop assistant.`,
      `I married just before I was 20, and travelled to some interesting places around the world, following my husband’s career. I spent much time reading, a passion, but in order to keep further occupied I took office jobs when these were available to me; I hated the work, but the money was useful.`,
      `When we were back in the UK I took evening classes at various times and gained ‘A’ levels in Psychology, Sociology and English, eventually settling in Kent with my husband and becoming a mature student and gaining Bachelor's and Master's degrees in English and Literature before training and working as a teacher.`,
      `In 2016 we moved to the peace and quiet of rural Lincolnshire, and my sporadic writing activities became more permanent. I self-published Fairytales Don't Come True, my debut novel, in May 2020 and since then have written and published four books of poetry, October Poems, Thanksgiving Poems & Prose Pieces, Poet-Pourri and Social Climbing and Other Poems.`,
      `In January 2021 I published a sequel to Fairytales entitled Degenerate, Regenerate, and at the end of March 2021 I published a psychological suspense story, You Know What You Did. A third book was published in June 2021, entitled All That We Are Heir To, to make up the 'Criminal Conversation' trilogy with Fairytales and Degenerate, In November 2022 I published another psychological suspense story, What Else Did You Do?, which is a sequel to You Know What You Did. The work didn't stop, as alongside this sequel I was writing a fourth book to follow the 'Criminal Conversation' trilogy. Entitled 'Innocent, Guilty'. It was published in January 2023, and a fifth book, 'The Future of Our House' came out in June 2023. The sixth and final book in the series is my current work in progress. I try to go for a long walk each day (weather permitting; I’m a fair-weather walker) in the beautiful countryside around us, and exercise for a couple of hours each morning, including use of a hula-hoop and stepping machine. I love food and drink and have spent half my life battling a weight problem. I managed to lose 5 stone of unfortunately-gained weight a few years ago and am determined to never regain it, Unfortunately however Covid and lockdown thwarted those plans, but at least I haven't put it all back on. Hopefully in 2023 I will manage to lose the excess. Life's certainly not fair in that respect, as every other day is a diet day (for hubby too) but the weight still came back. When not being careful--more often than is desirable these days--we enjoy a good meal with wine.`,
      `For other leisure activities I have taught myself to play the recorder--badly, but it keeps the brain cells ticking over. I also listen to music of many types; Tracy Chapman is playing while I write this, and will later be replaced by Leonard Cohen or Katie Melua or any one of dozens of other artists, or by some classical music or opera, another passion.`,
      `And of course there’s reading, something which I have loved since I was a child. I became a convert to eBooks and subscribed to the Kindle Unlimited programme, because although I love physical books, my bookcases are groaning under the weight and I don’t have room for any more. I review everything I read, since I became an author myself and realise the value of these in getting our work in front of as many eyes as possible; but it does mean that I have a large virtual To Be Read pile!`,
      `In late 2021 I undertook some editorial training and freelance work as a sub-editor. I terminated that work in late 2022, but have my hands full with writing my own books and reviewing those of others. Life is busy and certainly not boring.`,
    ],
  },
  {
    firstName: "Ian",
    lastName: "Hornett",
    email: "Ianhornettofficial@gmail.com",
    website: "https://ianhornett.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/ianhornett/",
      facebook: "https://www.facebook.com/ianmichaelhornett",
    },
    umbrellaGenre: ["comedy", "scifi"],
    subGenre: ["Dsytopian Sci-Fi", "Spy Comedy"],
    bio: [
      `A former customs officer turned teacher turned retired teacher, Ian came relatively late to writing. Now he’s doing it, he really rather enjoys it, writing novels, blogs and 100-word stories. His love of reading is reflected in his novels, having written a sci-fi trilogy with a dystopian twist and a comedy spy series about an octogenarian grandmother who gets called back into the Secret Service. 
2 books for children are also written and raring to go.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Marco",
    lastName: "Marek",
    email: "marcomarek77@gmail.com",
    website: "https://marcomarek77.wixsite.com/marcomarek",
    socialMedia: {
      instagram: "https://www.instagram.com/marcomarekauthor/",
      twitter: "https://twitter.com/1MarcoMarek",
      facebook: "https://www.facebook.com/MarcoMarekAuthor/",
    },
    umbrellaGenre: ["fantasy", "thriller"],
    subGenre: ["Urban Fantasy", "Suspense"],
    bio: [
      `Marco Marek is an award winning author from Italy. He always had a fervid imagination and a passion for fantasy stories, medieval magicians, ancient history, and unexplained mysteries. While he was visiting a castle in Eastern Europe, he had the idea of writing Hyperearth. He wrote five books and a short story. Apart from writing, Marco is also a painter and photographer, he likes digital artwork on Photoshop. He loves traveling when he has some free time.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Carla",
    lastName: "Reighard",
    email: "CarlasBooks88@yahoo.com",
    website: "https://carlasbooks.weebly.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/carlareighard/",
      facebook: "https://www.facebook.com/CReighardsbooks",
    },
    umbrellaGenre: ["fantasy", "scifi", "childrens"],
    subGenre: [
      "Fairy Tale Retellings",
      "Middle Grade Fantasy",
      "YA or Teen Fantasy",
      "Magical Realism",
    ],
    bio: [
      `Carla is a Colorado native where she currently lives with her husband. Imagination was a loyal childhood companion – a story always brewed inside her head. Until the publication of Elle’s Magical Shoes, the stories remained private.`,
      `Now Carla shares her wild imagination with the world as she travels in time, swims with the merfolk, flies over the island of the fae, delves into Viking myths, enters outer space, or invents a new perspective to familiar fairy tales. She hopes to teach young and old that age shouldn’t limit the ability to dream or to enjoy life.`,
    ],
    isVerified: true,
  },
  {
    firstName: "C A",
    lastName: "Deegan",
    email: "thecracklocksaga@outlook.com",
    website: "https://www.thecracklocksaga.com/",
    socialMedia: {
      twitter: "https://twitter.com/CracklockSaga",
      instagram: "https://www.instagram.com/thecracklocksaga/",
      facebook: "https://www.facebook.com/TheCracklockSaga",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["YA Fantasy", "Historical Fantasy", "Action/Adventure"],
    bio: [
      `I live in the East Midlands, right in the centre of the UK, and when I'm not writing or working, I'm with the family or walking the dog in the local woodlands seeking those ever-elusive Fae.  Or sitting, pint in hand, with the good friends I grew up with. Some are hidden in the books; quite a few characters are based on the people I know and love.`,
      `And so, to the Cracklocks… "The Cracklock Saga" series of books came about from reading some pretty awful fairy books to my daughter over the years – she's in her teens now and has (with more than a little relief, I have to say) left those behind.  But as I read those books with gritted teeth, I always wondered what would happen if someone didn't like fairies, what they would do about it, and could anybody stop them? This idea grew, and the Cracklocks were born.  I liked the idea of people who hated the Fae and everything they stood for.  And that world just keeps on growing.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Ann",
    lastName: "Thorsson",
    email: "ann.thorsson@gmail.com",
    website: "https://www.annthorsson.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/ann.thorsson.author/?hl=en",
      facebook: "https://www.facebook.com/ann.thorsson.author/",
      amazonBio:
        "https://www.amazon.co.uk/stores/Ann-Thorsson/author/B07V9XCNVZ",
    },
    umbrellaGenre: ["drama", "thriller"],
    subGenre: ["Contemporary Domestic Noir"],
    bio: [
      `Ann Thorsson was born in Chesterfield, UK. She now lives on a farm by the sea, nestled under the iconic Snæfellsjökull (Snaefells-glacier), on the West peninsula of Iceland, with her Icelandic husband, their two bilingual sons, an elderly Siberian husky and two wacky pups.`,
      `Ann has published three novels - gritty, contemporary, domestic noir dramas: Downhill, Dark Dreams, and Dark Shadows`,
    ],
    isVerified: true,
  },
  {
    firstName: "Marlene",
    lastName: "Cheng",
    email: "marlene.cheng@telus.net",
    website: "https://www.marlenecheng.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/memoir.cheng/",
      goodreads: "https://www.goodreads.com/marlenecheng",
      amazonBio:
        "https://www.amazon.com/stores/Marlene-F-Cheng/author/B071RJ57XS",
      bookbub: "https://www.bookbub.com/profile/marlene-f-cheng",
    },
    umbrellaGenre: ["drama", "historicalfiction"],
    subGenre: ["Women's Fiction", "Literary Fiction", "Historical Fiction"],
    bio: [
      `Marlene Cheng is a Wall Street Journal, Barnes and Noble, and Amazon bestseller. She, also, has Maincrest Media and Book Excellence awards in women's fiction.`,
      `Her fiction books are about the relationships that define women's lives--romance, friendship, and family. Marlene is a keen observer of how people think and feel and writes lyrical, uplifting, and emotionally rich stories.`,
      `Marlene was prairie-born, farm-raised, and now lives among the old-growth pine and cedar, overlooking the Pacific Ocean, on the West Coast of Canada—a haven that stimulates creativity.`,
      `“As with any worthy story,” Marlene says, “my biography has its inner destiny independent of its author. I sense this and strive for poise, integrity, and courage to go with the flow.”`,
    ],
    isVerified: true,
  },
  {
    firstName: "Charlene",
    lastName: "Mattson",
    email: "shaimatt0@gmail.com",
    website: null,
    socialMedia: {
      facebook: "https://www.facebook.com/TheFairyTaleCaseFiles",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Mystery"],
    bio: [
      `Charlene Mattson lives in Prince George, British Columbia with a house full of people and pets and a job full of more people which is an odd thing for an introvert to surround herself by. She writes primarily fantasy and fantasy/mystery, with the occasional foray into science fiction and poetry and works as an instructor teaching computer courses to finance her inability to market herself and a slight Starbucks addiction. She enjoys playing video games, table top rpgs, traveling, annoying two sons and making terrible jokes.`,
    ],
  },
  {
    firstName: "Terry Ann",
    lastName: "Taylor",
    email: "terry@ttaylor.me",
    website: "https://www.ttaylor.me/",
    socialMedia: {
      instagram: "https://www.instagram.com/terryanntaylor_regency/",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Historical Romance"],
    bio: [
      `Historic Storyteller - Home of the feisty Olivia Featherstone — Regency Adventures`,
      `Writing stories with strong-willed and courageous heroines`,
    ],
    isVerified: true,
  },
  {
    firstName: "M.L.",
    lastName: "Eaden",
    email: "douglasillusions@gmail.com",
    website: "https://mleaden.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/m.l.eaden/",
      facebook: "https://www.facebook.com/mleadenauthor",
      twitter: "https://twitter.com/ml_eaden",
    },
    umbrellaGenre: ["romance", "fantasy", "scifi"],
    subGenre: ["Urban Fantasy"],
    bio: [
      `M.L. Eaden works by day in the tech industry, but at night, she reads books, writes stories, throws axes, and is an avid gamer with a current addiction to Azul. Originally from the sunflower state, she migrated to one with a lone star—and more sun. She tries desperately to keep up with two adorable cattle dogs that still act like they are five instead of the seniors their vet says they are.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Katrina",
    lastName: "Goforth",
    email: "contact@authorkatrinagoforth.com",
    website: "http://authorkatrinagoforth.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/katrinagoforthwrites/",
      facebook: "https://www.facebook.com/KatrinaGWrites",
    },
    umbrellaGenre: ["fantasy", "childrens"],
    subGenre: ["Middle Grade", "Adventure"],
    bio: [
      `Katrina Goforth is the author of debut middle grade adventure Gate of Rose and Vine, Book One in the Beyond the Gate Series. Book Two, Trail of Sand and Stone is scheduled to release Fall 2023.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Vicky",
    lastName: "Peplow",
    email: "vicky.peplow1978@gmail.com",
    website: "https://vickypeplow1978.wixsite.com/vapbooks",
    socialMedia: {
      instagram: "https://www.instagram.com/vickypeplow/",
      facebook: "https://www.facebook.com/peplow1978/",
      twitter: "https://twitter.com/Vapbooks",
      tiktok: "https://www.tiktok.com/@vickypeplow",
      goodreads: "https://www.goodreads.com/vapbooks",
    },
    umbrellaGenre: ["horror"],
    subGenre: ["Paranormal", "Historical Fiction", "Crime", "Short Stories"],
    bio: [
      `Vicky Peplow was born and bred in an old coal mining village in the North-east of England. Her love for her roots has inspired her to write books that capture the essence of her hometown. She moved to Virginia, USA, to be with her soul mate, and it was there that she discovered her passion for writing. In just four years, she has made a name for herself in the literary world and is now a rising star to watch out for.`,
      `Vicky's primary interests are graphic design, reading, and sports. She has a keen eye for design and has used her talent to create stunning book covers that perfectly capture the essence of her stories. Her love for reading has helped her develop a unique writing style that is both captivating and engaging. She is also a sports enthusiast and loves nothing more than watching her favorite teams play. Despite being new to the writing scene, Vicky has already achieved a lot. Her books have received critical acclaim, and readers have fallen in love with her relatable characters and heartwarming stories. Her writing style is fresh and unique, and she has quickly become a favorite among readers of all ages. Apart from writing, Vicky has a great fondness for animals of all shapes and sizes. She is a proud owner of a ten-year-old long-haired dachshund, Sir Milo, and a cat named Leo.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Amanda",
    lastName: "Sheridan",
    email: "amandasheridan315@gmail.com",
    website: null,
    socialMedia: {
      instagram: "https://www.instagram.com/amandasheridanauthor/",
      twitter: "https://twitter.com/amandas26597105",
      facebook: "https://www.facebook.com/profile.php?id=100063878022530",
    },
    umbrellaGenre: ["thriller"],
    subGenre: [
      "Psychological Thrillers",
      "Espionage Drama",
      "Paranormal",
      "Lucid Dreaming",
      "Romance",
    ],
    bio: [
      `I’m a retired civil servant and I live on the beautiful Ards peninsula in Co. Down, Northern Ireland with my husband and our two rough collies.
I'm an avid fan of motorsports – F1, MotoGP and Superbikes, and up until 2018, I frequently attended races in Europe.
Reading has always been a hobby of mine and I love nothing better than escaping into the world between the pages. 
Rapid Eye Movement is my first novel and I assumed it was a standalone until the idea for The Dreaming came to me. I followed this up with a third book in the series – Dream Catcher. I thought that was it, but this month I published Bad Dreams which is a Rapid Eye Movement spin-off about Lucy, one of the other characters in the first book.`,
    ],
  },
  {
    firstName: "H. M.",
    lastName: "Mills",
    email: "h.m.mills.pdfa@gmail.com",
    website: "https://hmmillsbooks.wixsite.com/hmmills",
    socialMedia: {
      instagram: "https://www.instagram.com/h.m.mills_author/",
      twitter: "https://twitter.com/HMMills203",
      facebook: "https://www.facebook.com/HMMillsBooks/",
      tiktok: "https://www.tiktok.com/@authorhmmills",
      goodreads:
        "https://www.goodreads.com/books/show/57303793-mercy-on-your-soul",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Paranormal Dark Fantasy Romance"],
    bio: [
      `Award winning author & lover of Paranormal Dark Fantasy Romance & an avid reader, living in Tasmania Australia. 
Currently working on Book 3 of The Mercy Aymes Series & edits on two standalones.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Bruce",
    lastName: "Spydar",
    email: "brucespydar@gmail.com",
    website: "http://www.brucespydar.wordpress.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/brucespydar",
    },
    umbrellaGenre: ["romance", "comedy", "nonfiction"],
    subGenre: ["Humour", "Rom-Com", "Self-Help"],
    bio: [
      `Bruce Spydar used to wear a suit, work in an office, and get paid to lead teams of staff working for international nature conservation.  Today he possesses no suit that fits, has no office nor staff, and he doesn’t get paid … although he still volunteers in support of nature.`,
      `For the last few years, Bruce has thrown himself into writing.  Perhaps it’s a last-ditch attempt to harness his creativity before his brain turns to mush.  On many an afternoon he can be spotted gazing out of an upstairs window of his house near Cambridge, searching for inspiration.`,
      `Bruce describes himself as writing with a kind heart and a naughty mind.  Personal experience has taught him that everyday life is rather full of struggles, and that happiness and laughter are too often in short supply.  It’s why he now chooses to focus his creativity towards sharing his humour and positivity.`,
    ],
    isVerified: true,
  },
  {
    firstName: "A.S.",
    lastName: "Urban",
    email: "asurbanbooks@gmail.com",
    website: "https://as-urban.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/asurbanbooks/",
      goodreads: "https://www.goodreads.com/author/show/22675430.A_S_Urban",
    },
    umbrellaGenre: ["scifi"],
    subGenre: ["Military", "Space Fleet", "Romance", "Adventure"],
    bio: [
      `Her mother had the difficult task of telling five-year old A.S. she was blind as bat. Astronauts don't wear glasses. The allure of space and all the adventures to be had there still tickle her imagination. Pair her love of all things outer space with her love of the courtship romance novels and you get  the Corvus Squadron Universe.`,
      `A.S. lives in the Northwest with her husband, twin girls, and the orange tabby Frank.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Carrie",
    lastName: "Scharf",
    email: "carrieshandmadeessentials@gmail.com",
    website: "https://carriescharf.blogspot.com/",
    socialMedia: {
      instagram: "https://instagram.com/carrieclarinet",
      facebook: "https://www.facebook.com/ChandmadeEssentials/",
      twitter: "https://twitter.com/carrieclarinet",
      amazonBio:
        "https://www.amazon.com/stores/Carrie-Scharf/author/B09ZQ77LTL?ref=ap_rdr&isDramIntegrated=true&shoppingPortalEnabled=true",
      threads: "https://threads.com/carrieclarinet",
    },
    umbrellaGenre: ["nonfiction"],
    subGenre: ["Skincare"],
    bio: [
      `Carrie Scharf has a skincare business and is the author of Carrie's Herbal Infused Skincare Cookbook.  Carrie's experience making skincare and experimenting with ingredients inspired her to write her books.`,
      `Carrie has degrees from Mayland Community College and the University of North Carolina at Asheville.  Carrie lives and works out of her home in West Virginia.  She homeschools her two boys and plays clarinet in the Charleston Metro Band`,
    ],
    isVerified: true,
  },
  {
    firstName: "Helen",
    lastName: "Garraway",
    email: "helen@helengarraway.com",
    website: "http://www.helengarraway.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/helengarrawayauthor/",
      facebook: "https://www.facebook.com/helengarrawayauthor/",
      goodreads: "https://www.goodreads.com/helengarrawayauthor",
      amazonBio: "https://www.amazon.com/stores/author/B08JQPPK3Z",
      bookbub: "https://www.bookbub.com/authors/helen-garraway",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Epic Fantasy", "Fantasy Romance"],
    bio: [
      `Helen Garraway is the USA Today Bestselling author of the award winning epic fantasy Sentinal series which was first published in 2020, followed by the first book of the fantasy romance SoulMist series, SoulBreather, released in 2022 as part of the Realm of Darkness boxset.`,
      `An avid reader of many different fiction genres, a love she inherited from her mother, Helen writes fantasy novels and also enjoys paper crafting and scrapbooking as an escape from the pressure of the day job.`,
      `Having graduated from the University of Southampton with a Degree in Politics and International Relations, she remains an active member of their alumni.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Nicky F",
    lastName: "Webber",
    email: "author@nickywebber.com",
    website: "https://nickywebber.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/nickywebbernz/",
      facebook: "https://www.facebook.com/nickywebbernz",
      twitter: "https://twitter.com/nicky_author",
      tiktok: "https://www.tiktok.com/nickywebberauthor",
      amazonBio: "https://www.amazon.com/stores/author/B07N189YNH",
    },
    umbrellaGenre: ["romance", "thriller", "drama"],
    subGenre: ["Suspense", "Psychological Thriller", "Domestic Thriller"],
    bio: [
      `Nicky Webber is an award-winning author of Contemporary, Historical and Suspense Thrillers. She received international acclaim for her novel Duplicity, and Honourable Mention in the USA 2022 Top Shelf Magazine Awards for Fiction.  She also writes psychological thrillers under the name N F Webber.`,
      `With her background in journalism, Nicky is a master at crafting suspenseful and emotionally-rich stories, filled with intrigue and a touch of romance.`,
      `For more details and to subscribe to her monthly newsletter visit
www.nickywebber.com`,
    ],
    isVerified: true,
  },
  {
    firstName: "Jenn",
    lastName: "Howlett",
    email: "jenn.howlett@icloud.com",
    website: "https://jennhowlett.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/jenn.howlett.author/",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Paranormal/Fantasy Romance"],
    bio: [
      `I started writing after being convinced by Lee Child that, as a reader, I am also a writer. I had been reading and reviewing books via the (now reduntant) Eternal Bookcase blog for well over two years and during a reading slump a good friend recommended I read something completely different.`,
      `My eyes were opened to the realm of monster-erotic fiction and after reading a fair handful of them, I thought; ‘I could do better than that!’ So, here I am, attempting to do so. I have no formal literary qualifications, just heaps of enthusiasm for telling and consuming stories.`,
      `While not writing, daydreaming, or plotting, I volunteer for a local charity shop—which helps keep me both social and grounded. I also own a Barley Dog and am a Mother-of-One.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Leon",
    lastName: "Stevens",
    email: "linesbyleon@gmail.com",
    website: "https://www.linesbyleon.com/",
    socialMedia: {
      twitter: "https://www.twitter.com/linesbyLeon",
      instagram: "https://www.instagram.com/lines_by_leon",
    },
    umbrellaGenre: ["scifi"],
    subGenre: ["Science Fiction", "Poetry"],
    bio: [
      `Leon Stevens is a multi-genre author, composer, guitarist, and artist, with a Bachelor of Music and Education. He published his first book of poetry in 2020, followed by a book of original classical guitar compositions and a short story collection of science fiction/post-apocalyptic tales. His newest publications are the sci-fi trilogy, The View from Here, and a new collection of poetry titled, A Wonder of Words.`,
    ],
  },
  {
    firstName: "E. M.",
    lastName: "Leander",
    email: "leander@emleander.com",
    website: "http://www.emleander.com/",
    socialMedia: {
      twitter: "https://twitter.com/EMLeander1",
      instagram: "https://www.instagram.com/e.m.leander/",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Epic Fantasy", "Fantasy Romance"],
    bio: [
      `E. M. Leander lives in the American South with her husband, two children, and a grumpy old cat. A life-long lover of all things literary, when she’s not spending free time with family, she can be found devouring books and coffee in equal measure.`,
    ],
    isVerified: true,
  },
  {
    firstName: "T.A.",
    lastName: "Rosewood",
    email: "traci@tarosewood.com",
    website: "https://www.tarosewood.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/tarosewood/",
      facebook: "https://www.facebook.com/tarosewood/",
      twitter: "https://www.twitter.com/tarosewood/",
      tiktok: "https://www.tiktok.com/@tarosewoodauthor",
    },
    umbrellaGenre: ["romance", "thriller", "drama"],
    subGenre: ["Women's Fiction"],
    bio: [
      `Hi there. I'm Traci...AKA, T.A. Rosewood and I write relatable, emotional fiction with lovable characters and heartwarming storylines that stay with you for a long time afterwards.`,
      `Born, bred and still living in the north of Essex, England, with my very patient and supportive husband, children, and Robbie, the Westie.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Pat",
    lastName: "Backley",
    email: "hello@patbackley.com",
    website: "https://www.patbackley.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/patbackleyauthor",
      facebook: "https://www.facebook.com/patbackleyauthor",
      twitter: "https://www.twitter.com/patbackleybooks",
    },
    umbrellaGenre: ["drama", "nonfiction"],
    subGenre: ["Historical", "Memoirs", "Self-Help"],
    bio: [
      `Pat Backley is English but emigrated to New Zealand when she was 59. She wrote and published her first book just before her 70th birthday and having discovered her passion she now intends to write till she dies!`,
      `She has lived a colourful and interesting life and her books, both fiction and non-fiction, reflect her passionate love of people and travel.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Joelle",
    lastName: "Cullen",
    email: "joelle.cullen.author@gmail.com",
    website: "https://joellecullen.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/coffeeshopcorner/",
      facebook:
        "https://www.facebook.com/profile.php?id=100085705707451&mibextid=ZbWKwL",
      tiktok: "https://www.tiktok.com/@joellecullenauthor",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Women's Fiction"],
    bio: [
      `Joelle Cullen has dreamt of becoming an author since she was a little girl. Following years of encouragement from her husband, she finally took the plunge into the author life in 2021. After many visits to the library paired with a white chocolate mocha latte (and a little help with supervision from her children's teachers), she finally completed her first novel set in her favorite place, London.`,
      `Joelle graduated summa cum laude from SUNY Geneseo and Syracuse University, with a BA in History and Education, and a MS in Special Education. She shared her love of history with hundreds of middle school students  before staying home and raising her four children.`,
      `Now she spends her time writing, playing piano, reviewing books on her bookstagram page, and shuttling her kids from activity to activity. She might complain about the mess that gets made, but her kids and husband are the best parts of her life.`,
    ],
  },
  {
    firstName: "Daniel",
    lastName: "Bautz",
    email: "dbautzy@aol.com",
    website: "https://www.danielbautzctp.com/",
    socialMedia: {
      instagram: "https://instagram.com/dbautzy",
    },
    umbrellaGenre: ["horror"],
    subGenre: ["Historical", "Adventure", "Thriller"],
    bio: [
      `Daniel's award-winning debut, Life is in the Blood, is an astounding achievement in storytelling from Anatolian Press. His short story, Made of Clay, is featured in the Horror Anthology, Autumn Tales, with nine other fantastic authors and their spectral yarns.`,
      `Daniel has done it all.`,
      `He has worked as a graphic designer, a podcast & radio host, a writer and a director of film. He is a true creative type. While he enjoyed all of these endeavors, those accomplishments pale in comparison to his true calling - the written word.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Tory",
    lastName: "Richards",
    email: "toryrichards60@gmail.com",
    website: "http://www.toryrichards.com/",
    socialMedia: {
      twitter: "https://twitter.com/ToryRichards",
      instagram: "https://www.instagram.com/toryrichards60/",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Interracial", "Contemporary", "Suspense", "Paranormal"],
    bio: [
      `Tory Richards is an author who writes smut with a plot. She's an Amazon bestselling author in erotic romance and romantic suspense categories. Born in Maine, she's lived most of her life in Florida where she went to school, married, and raised her daughter. She's retired from Disney and spends her time with family and friends, traveling, and writing.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Alycin",
    lastName: "Hayes",
    email: "alycinhayes@gmail.com",
    website: "https://www.echohillproductions.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/alycin.hayes",
      twitter: "https://twitter.com/AlycinHayes",
      instagram: "https://www.instagram.com/alycinhayes.adventurer/",
    },
    umbrellaGenre: ["childrens", "nonfiction"],
    subGenre: ["Adventure", "Travel Memoir"],
    bio: [
      `Alycin Hayes is a writer of poetry, prose and song, a singer, actress, filmmaker, producer and a wildlife conservationist. Her articles on animal behavior research have been published internationally.`,
      `She is the author of the award winning children's book "Milo and The Mustang", winner of the 2020 R. Morrow Book Award for "Great Kid Books for Road Trips"`,
      `Alycin’s poetry has been displayed at the Gainesville Fine Arts Association Art Gallery in Gainesville, Florida.`,
      `Her article "Writing About Travel, Writing About Journeys'' was published in the Writers Alliance of Gainesville's blog "Hogtown Quill". She was an exhibitor at the Sunshine State Book Festival for several years and a guest speaker last year.`,
      `Alycin’s internationally popular adventure travel memoir "Amazon Hitchhiker: A Woman’s Adventures from Canada to Brazil" is the extraordinary true story of her adventures hitchhiking alone in the 1970’s from Canada to South America where she became lost paddling a leaky dugout canoe into the rivers and mystical rainforests of the wild Amazon Basin.`,
      `For more information about Alycin Hayes go to her website: https://www.echohillproductions.com/contributor-bios.html`,
    ],
    isVerified: true,
  },
  {
    firstName: "Jessica",
    lastName: "Piro",
    email: "pirojessica@yahoo.com",
    website: "https://www.jessicapiro.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/xdrag0n0vax/",
      twitter: "https://twitter.com/xDRAG0N0VAx",
    },
    umbrellaGenre: ["thriller"],
    subGenre: ["Suspense", "Action"],
    bio: [
      `Jessica is a writer in a wheelchair and has Type 1 Diabetes. She is a multi-genre author and her works cater to YA, NA, and Adults.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Maia",
    lastName: "Terry",
    email: "maiaterryauthor@hotmail.com",
    website: "http://authormaiaterry.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/authormaiaterry/",
      tiktok: "https://www.tiktok.com/@maiaterryauthor",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["YA Contemporary", "Spicy Mafia"],
    bio: [
      `Maia Terry is a small town author from Kentucky where she lives with her husband and two amazing kids. Picking up writing at a young age, Maia loved creating a world that she could control, one where she could escape. Now, after a fourteen year hiatus, she builds on that love as she continues to use writing as an outlet. The real life aspects in her works hit home for so many, allowing them to connect on a deeper level with each character. Writing not only allowed herself to escape, but she wanted to create a world where she could give that reprieve to others as well.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Madeline",
    lastName: "Vaughn",
    email: "madelinevaughnbooks@gmail.com",
    website: "https://www.madelinevaughnbooks.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/madelinevaughnbooks/",
    },
    umbrellaGenre: ["thriller"],
    subGenre: ["Crime", "Suspense"],
    bio: [
      `I'm Madeline Vaughn from Kansas City, MO. I have always been passionate about writing and storytelling. I would describe myself as a curious author who loves exploring different themes and motifs. As part of my writing process, I love to immerse myself into my projects—dive headfirst into the research, production, and fine-tuning of the stories that I feel are the most worthy of telling.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Kathy",
    lastName: "Brandon",
    email: "Kathy.Brandon.author@gmail.com",
    website: "https://kathybrandonauthor.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/kathy.brandon.author.1222/",
      goodreads: "https://www.goodreads.com/author/show/15584103.Kathy_Brandon",
    },
    umbrellaGenre: ["childrens"],
    subGenre: ["Community"],
    bio: [
      `When Kathy became an educator, it was an easy transition to spread the joy of reading to students of all ages, knowing that there was a genre and book out there for every child to delve into with enthusiasm. Opening the pages of a book is the start of a brand new adventure for children and Kathy knew she wanted to contribute to the excitement children feel when they do so, as well as, sharing her passion for community, nature and animals. When she decided to write her first book, it was important to combine reading and interactive learning through a guide for children and adults to engage as well. She has three children, three in-laws and three grandsons who all bring her immense joy, adventures and so much laughter. With her husband and four-legged companion, you will find them all on the trails as much as possible, exploring the sights, sounds, smells and touch of nature all around them.`,
    ],
  },
  {
    firstName: "Kirk",
    lastName: "Burris",
    email: "kb@kirkburris.com",
    website: "https://www.kirkburris.com/",
    socialMedia: {
      twitter: "https://twitter.com/BurrisKirk",
      facebook: "https://www.facebook.com/KirkBurrisAuthor",
      instagram: "https://www.instagram.com/kirkburrisauthor",
    },
    umbrellaGenre: ["thriller"],
    subGenre: ["Mystery"],
    bio: [
      `Multi-genre author Kirk Burris is an Amazon Best-selling author. His Book, 12 PILLS, cracked the top 100 Mystery books in 2022, landing him a space right between James Patterson and Michael Connelly. This was a huge honor as both of those authors are among his favorites.`,
      `Having grown up in Missouri, where he earned a B.A. in Psychology from the University of Missouri, Kirk now makes his home in South Florida and swears he doesn't miss shoveling snow and ice to free his car. A fan of Kansas City, it has become the primary backdrop to his books thus far, though they also explore Miami, Washington D.C. and his romantic favorite, Paris, France.`,
      `A travel bug, Kirk is often abroad. He can be found snorkeling the waters of the Caribbean, walking the streets of Paris, or taking in a Broadway show in New York. At home, Kirk is a food and cooking enthusiast. He also enjoys zipping along the exhilarating tracks of major roller coasters while he plots his next adventure.`,
    ],
  },
  {
    firstName: "Haley Anna",
    lastName: "Marie",
    email: "elementasseries@protonmail.com",
    website: "https://www.elementasseries.com/",
    socialMedia: {
      twitter: "https://twitter.com/ElementasSeries",
      facebook: "https://www.facebook.com/elementasseries/",
      instagram: "https://www.instagram.com/ElementasSeries/",
      tiktok: "https://www.tiktok.com/@authorofelementasseries",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Dark Fantasy"],
    bio: [
      `Due to childhood deafness, I would create stories to match the pictures in the books. Once my hearing was corrected, I fell in love with stories. In fourth grade, I wrote six short stories, and in fifth grade, I singlehandedly wrote and performed in a school play. The fantasy series, Elementas, is my prized possession, and I can't wait to share all of it with the world.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Felicity",
    lastName: "Niven",
    email: "felicity@felicityniven.com",
    website: "https://www.felicityniven.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/felicityniven",
      instagram: "https://www.instagram.com/felicitynivenauthor/",
      tiktok: "https://www.tiktok.com/@felicitynivenauthor",
      amazonBio:
        "https://www.amazon.com/stores/Felicity%20Niven/author/B0B9Q7ST5C",
      bookbub: "https://www.bookbub.com/authors/felicity-niven",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Steamy Historical Romance", "Regency Romance"],
    bio: [
      `Felicity Niven is a hopeful romantic. Writing Regency romance is her third career after two degrees from Harvard. And you know what they say about third things? Yep, it’s a charm. She splits her time between the temperate South in the winter and the cool Great Lakes in the summer and thinks there can be no greater comforts than a pot of soup on the stove, a set of clean sheets on the bed, and a Jimmy Stewart film on a screen in the living room. "Felicity Niven's writing is sharp and exquisite." — Julia Quinn`,
    ],
    isVerified: true,
  },
  {
    firstName: "Krystal",
    lastName: "Harris",
    email: "authorkrystalharris@gmail.com",
    website: "https://theimpatientalpaca.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/maraca_the_alpaca/",
      facebook: "https://www.facebook.com/profile.php?id=100086266890541",
      amazonBio:
        "https://www.amazon.ca/stores/Krystal-Harris/author/B0BG3CB8Z9",
    },
    umbrellaGenre: ["childrens"],
    subGenre: ["Picture Book"],
    bio: [
      `Author Krystal Harris never imagined herself as a children’s book author. She started writing after her daughter was born, and likes to think that her daughter was and continues to be her inspiration. The most important aspect of every story Krystal writes, is that it must have a strong message and lesson to inspire her young readers—she truly believes that there is a lesson to be learned from everything.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Alivia",
    lastName: "Fleur",
    email: "alivia@aliviafleur.com",
    website: "https://aliviafleur.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/aliviafleur_writes/",
      facebook: "https://www.facebook.com/aliviafleurwrites",
      goodreads: "https://www.goodreads.com/alivia-fleur",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Historical Romance"],
    bio: [
      `2023 RUBY winner for Best Historical Novella`,
      `Alivia is a historical romance author who moved form writing short stories to novels when her characters kept showing up with copious amounts of emotional baggage, demanding it be explored. Her love of the Victorian era, combined with a flair for creating memorable characters, led her to start writing her first historical romance series, Tales from Honeysuckle Street.`,
      `Alivia lives on a farm along way from anywhere interesting, with her husband, four dogs, and a charismatic chicken named Persephone.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Lyv",
    lastName: "Lamere",
    email: "lyvlamere@gmx.net",
    website: "https://www.lyvlamere.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/lyvlamere/",
      amazonBio: "https://www.amazon.com/stores/author/B0C8J8NS2X",
      bookbub: "https://www.bookbub.com/authors/lyv-lamere",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "Instalove", "Low-Angst", "Erotica"],
    bio: [
      `Lyv Lamere grew up in Germany and still lives there with her husband, their two cats, and her snake, even though they plan to relocate in the future.`,
      `After successfully studying veterinary medicine and working at a laboratory, and working as a contractor in the tech industry, one day she found she had developed yet another passion – writing – and her first novel was completed sooner than expected.
She's currently focusing on writing her second novel.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Marie",
    lastName: "Landry",
    email: "sweetmarie.landry@gmail.com",
    website: "https://www.marielandryauthor.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/marielandry.author/",
      facebook: "https://www.facebook.com/MarieLandryAuthor/",
      tiktok: "https://www.tiktok.com/@marielandrybooks",
      amazonBio: "https://www.amazon.com/author/marielandry",
      threads: "https://www.threads.net/@marielandry.author",
      bookbub: "https://www.bookbub.com/profile/marie-landry",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary Romance", "Romantic Comedy"],
    bio: [
      `Marie Landry lives and writes in a cozy apartment in Ontario, Canada, surrounded by books and Funko Pops. An avid reader from a young age, she loves getting lost in characters’ worlds, whether they’re of her own making or someone else’s. She particularly loves stories with as much of an emphasis on self-discovery and friendship as on romance...but don’t leave out the romance!`,
      `When not doing bookish things, you can often find her taking pictures, cooking, scrolling Instagram (find her at @marielandry.author), daydreaming about frolicking through the Scottish Highlands, or listening to the same music she's loved since the '90s. She's an unapologetic nerd and fangirl, and that, along with her mental health advocacy, is often woven into her books.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Matthew",
    lastName: "Romeo",
    email: "themavenknight@gmail.com",
    website: "https://themavenknight.wixsite.com/website",
    socialMedia: {
      instagram: "https://www.instagram.com/housemontegue/",
      facebook: "https://www.facebook.com/housemontegue/",
    },
    umbrellaGenre: ["scifi"],
    subGenre: ["Fantasy", "Thriller"],
    bio: [
      `Matthew Romeo is a warrior poet. He has a healthy obsession with Star Wars, the Stormlight Archive, Cobra Kai, and Halo. When it comes to his career as a writer, he’s been inspired by the likes of Frank Herbert, Bandon Sanderson, and Pierce Brown. Pure chaos is the way of his writing style, often flitting between methodical outlining or just winging the story as he goes. Outside of being an author, he works for an international shipping company, is a loving husband, and a dad of two cats named Korra and Toph. He spends much of his free time playing Dungeons&Dragons, learning swordsmanship, practicing martial arts, and crafting entertaining stories.`,
    ],
    isVerified: true,
  },
  {
    firstName: "SF",
    lastName: "Benson",
    email: "sfbenson@authorsfbenson.com",
    website: "https://www.authorsfbenson.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/authorsfbenson/",
      facebook: "https://www.facebook.com/BensonSF/",
      twitter: "https://twitter.com/BensonShantella",
    },
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["Romantic Fantasy"],
    bio: [
      `SF Benson, the talented author behind the captivating paranormal suspense series, The Spell Caster Diaries, resides in sunny Southern California with her husband and daughter, despite her extensive knowledge of Falls Creek, New York, and its supernatural inhabitants. When she isn't crafting stories of resilient heroes and heroines overcoming challenges, she indulges in her passion for romance and fantasy novels or immerses herself in her favorite DC Universe shows and Marvel movies.`,
    ],
  },
  {
    firstName: "Richard",
    lastName: "Houlden",
    email: "rickyh92@gmail.com",
    website: "https://richardhouldenauthor.wordpress.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/richhoulden/",
    },
    umbrellaGenre: ["fantasy", "scifi"],
    subGenre: ["Short Story", "Anthology"],
    bio: [
      `I’m a self published, indie author from West Yorkshire, UK.`,
      `Though my career is in finance, I’ve always yearned to be an author with a passion for writing being discovered at a very young age. Of all the genres, I gravitate toward science fiction primarily because of the freedom and range of possibilities available to me.`,
      `Though I started writing with the aim of full length novels, releasing my first in June 2022, I’ve developed a great love for short stories and the little snippets of excitement I can bring with the release of The Cartographer’s Vault in June 2023.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Danielle",
    lastName: "Paquette-Harvey",
    email: "danielleauthorph@gmail.com",
    website: "http://www.daniellephauthor.com/",
    socialMedia: {
      instagram: "http://instagram.com/daniellephauthor/",
    },
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["Dark Fantasy Romance"],
    bio: [
      `Danielle Paquette-Harvey is an Award-Winning Amazon International Best Selling author of paranormal romance and steamy vampire romance fantasy. Her books include werewolves and vampires, myths and dark prophecies, magic, and witches, dragons and fairies, adventure and war, goddesses and demons. Her books have sold thousands of copies in 12 different countries worldwide and are being considered for a movie adaptation. Her books have been translated into French, and Italian. She is a self-published author living on the south shore of Montreal, Canada, with her husband, children, two cats, and an Australian Shepherd.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Marian",
    lastName: "Pattechat",
    email: "marian.pattechat@gmail.com",
    website: "https://www.marianpattechat.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/marianpattechat/",
      amazonBio: "https://www.amazon.com/stores/author/B0C19VRVNV",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Sci-Fi", "Fantasy"],
    bio: [
      `I write science fiction and fantasy romance books that are sweet, steamy, and sprinkled with a hearty dose of humor. Join my sassy heroines and cinnamon roll heroes as they discover new worlds - and love - together!`,
    ],
    isVerified: true,
  },
  {
    firstName: "Lilla",
    lastName: "Nicholas-Holt",
    email: "picketybooks@gmail.com",
    website: "http://picketybooks.com/",
    socialMedia: {
      facebook: "http://facebook.com/picketybooks",
      instagram: "https://www.instagram.com/picketybooks/",
      amazonBio:
        "https://www.amazon.com/stores/Lilla-Nicholas-Holt/author/B00GE1HYXU",
    },
    umbrellaGenre: ["childrens"],
    subGenre: ["Rhyming Children's Stories"],
    bio: [
      `Lilla is a New Zealand author who has self-published three novels; her latest, Soldier Sailor Lover Slave: A Story of a Woman's Nine Past Lives published under her maiden name, E F Holt. She has also self-published a collection of children’s stories, which she invites you to view on her website picketybooks.com. In her teenage years she wrote limericks with dark humour in birthday cards for friends and family, which delivered a few laughs.`,
      `The author grew up on a sheep farm in Waimate North, NZ, enjoying all the wonderful experiences and freedom of the great outdoors. Apart from enjoying her love of writing, she paints portraits, lately of her grandchildren, as well as creating “quiet books” for her grandchildren.`,
      `The concept of reincarnation fascinates her. She has read books written by Dr. Brian Weiss, Dr. Ian Stevenson, Edgar Cayce, and Shakti Gawain, but her favourite and most influential are the Seth Books written by Jane Roberts.`,
      `Lilla is responsible for three adult children and four grandchildren.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Elora",
    lastName: "Canne",
    email: "elora.canne@gmail.com",
    website: null,
    socialMedia: {
      instagram: "https://www.instagram.com/elora_canne",
      facebook: "https://www.facebook.com/eloracanne",
    },
    umbrellaGenre: ["nonfiction"],
    subGenre: ["Memoir", "Travel"],
    bio: [
      `Elora Canne originates from South Africa, now living in Sydney, Australia. Her memoir, En Route, outlines the travels of a gap year her and her husband took, to travel the world. EN ROUTE: The Best is Yet To Be, is available in ebook and paperback on Amazon.`,
      `~~Road trips and relationships, what could possibly go wrong?`,
    ],
  },
  {
    firstName: "AM",
    lastName: "Scott",
    email: "lightwavepub@gmail.com",
    website: "https://www.amscottwrites.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/amscottwrites/",
      facebook: "https://www.facebook.com/AMScottWrites/",
      twitter: "http://twitter.com/AM_Scottwrites",
    },
    umbrellaGenre: ["scifi"],
    subGenre: ["Space Opera"],
    bio: [
      `After twenty years as a US Air Force space operations officer, AM now operates a laptop, trading in real satellites for fictional spaceships. She writes classic-style science fiction for today’s world, full of adventure, hope and heart.`,
      `AM’s writing cave is deep in the mountains of western Montana; check out Montana, The Amazing Sleeping Man and Zoe, their slightly crazy German Shepherd, on Instagram. AM is also a volunteer leader with Team Rubicon Disaster Response.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Stacy",
    lastName: "Kristen",
    email: "stacykristenauthor@gmail.com",
    website: "https://www.stacykristenauthor.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/stacykristenauthor",
      facebook: "http://www.facebook.com/StacyKristenAuthor2",
      tiktok: "http://tiktok.com/@stacykristenauthor",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Romantic Suspense"],
    bio: [
      `Stacy Kristen is an indie author who writes spicy romance and romantic suspense novellas with HEAs for those who just want a short, steamy read. She's an avid reader of romance and enjoys baking, drinking lots of caffeine, traveling, and laughing at the squirrels in her backyard.`,
    ],
  },
  {
    firstName: "Christopher",
    lastName: "Candy",
    email: "christophercandy@icloud.com",
    website: "http://www.christophercandy.co.nz/",
    socialMedia: {
      instagram: "https://www.instagram.com/christophercandy.author/",
      facebook: "https://www.facebook.com/authorchristophercandy",
      twitter: "https://twitter.com/author_candy",
    },
    umbrellaGenre: ["childrens"],
    subGenre: ["Children's Picture Books"],
    bio: [
      `Christopher Candy. Author of the Comet the Red Bus book series. Including Around the City and Comet Goes to the Beach.`,
      `After the outstanding success of his first children's picture book, Comet the Red Bus - Around the City, Author Christopher Candy has continued to write the next book in the Comet the Red Bus series. Working full-time as a Manager for Tranzit Coachlines, Christopher has many years of bus-related experience that brings his characters to life. Christopher is based in the Tararua region and enjoys spending time with his partner, farm animals and pet dog, Tupance.`,
    ],
  },
  {
    firstName: "L.",
    lastName: "Cuzidora",
    email: "lcuzidora@gmail.com",
    website: "https://cuzidora.podia.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/l.cuzidora/",
    },
    umbrellaGenre: ["dystopian"],
    subGenre: ["Romance", "Thriller"],
    bio: [
      `L is a proud rat mother from Transylvania, Eastern Europe. She studied Sociology and Environmental Sciences and wishes she’d had started writing at an earlier age. Now she’s determined to make up for all the years spent jumping from one passion to another and devote herself to exploring even more flawed characters.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Anne M.",
    lastName: "Scott",
    email: "lightwavepub@gmail.com",
    website: "https://www.amscottwrites.com/romance/",
    socialMedia: {
      instagram: "https://www.instagram.com/annemscott_author",
      facebook: "https://www.facebook.com/AnneMScottAuthor",
      twitter: "https://twitter.com/AnneScottAuthor",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Romantic Suspense"],
    bio: [
      `After twenty years in the US Air Force, Anne M. Scott traded her sword for a pen. Well, a laptop. She writes about strong women and men, love that grows slowly in small western towns, with suspense, action and adventure, and anything more than kisses behind closed doors.`,
      `Anne is lucky to live, hike, and ski in the Bitterroot Mountains of Montana. On the rare occasions she leaves, Anne volunteers with Team Rubicon, a veteran-led disaster response organization.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Bonnie",
    lastName: "Callahan",
    email: "bonniecallahanbooks@gmail.com",
    website: "https://www.bonniecallahanbooks.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/authorbonniecallahan/",
      tiktok: "https://www.tiktok.com/@authorbonniecallahan",
    },
    umbrellaGenre: ["romance", "fantasy", "thriller", "historicalfiction"],
    subGenre: ["Romantic Comedy", "YA Historical Fiction", "Romantic Thriller"],
    bio: [
      `Bonnie was born in Tucson, Arizona, where she went on to study Classics and Italian at the University of Arizona. After seven years in Italy, she is now back in the Sonoran Desert, where she lives with her Italian study abroad sweetheart, their two kids, and a few bilingual pets. Bonnie is the author of Remy vs. Rome, a rom-com adventure novel, and Road of Stars and Flame, a YA historical fantasy. She is currently working on her first romantic thriller, based in a medieval Italian hill town and inspired by true events. Her idea of a happily ever after includes a solid serving of food, wine, and adorable animals.`,
    ],
  },
  {
    firstName: "Jessica",
    lastName: "Scachetti",
    email: "Jscachetti1984@yahoo.com",
    website: "https://jscachetti.wixsite.com/authorsite",
    socialMedia: {
      instagram: "https://www.instagram.com/jessica_scachetti_author/",
      facebook: "https://www.facebook.com/jessicascachettiromanceauthor/",
      twitter: "http://twitter.com/jessScachetti",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Christian"],
    bio: [
      `Writes gritty Christian romance books. Edgier Christian love stories containing sinful characters who make or have made poor choices. Despite each books use of flawed characters, violence and profanity, each gritty representation showcases the immorality of those sinful actions and displays an overall message of redemption and salvation through Jesus Christ.`,
      `Each of my books is part of a series of interconnected standalone novels/novellas, and you can find them exclusively on Amazon.`,
    ],
    isVerified: true,
  },
  {
    firstName: "D.H.",
    lastName: "Gibbs",
    email: "dhgibbsauthor@gmail.com",
    website: "http://www.dhgibbs.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/dhgibbs_author/",
      tiktok: "https://www.tiktok.com/@dhgibbsauthor",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Low Spice Fantasy"],
    bio: [
      `D.H. Gibbs is a USA Today Bestselling Author and Newsday T&T Choice finalist. She enjoys writing fantasy, contemporary romance, and children’s books. When not navigating the adventures of her kick-ass female leads, she’s a complete Starbucks and book addict who binge-watches TV series like Lucifer, Carnival Row, and Warrior. A Trinidadian native, she currently lives and creates new worlds in Japan.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Rebecca",
    lastName: "Marsh",
    email: "authorrebeccalmarsh@gmail.com",
    website: "https://www.rebeccalmarsh.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/RebeccaLynnMarsh",
      twitter: "https://twitter.com/RebeccaLMarsh1",
    },
    umbrellaGenre: ["drama"],
    subGenre: ["Women's Fiction"],
    bio: [
      `Rebecca L. Marsh is an award winning author of women's fiction and a member of the Paulding County Writer's Guild. She grew up in the mountains of Western North Carolina and now lives in Dallas, Georgia with her husband and daughter.`,
      `When not writing, she enjoys spending time with her family (cats and dog included), watching movies, and reading a good book. Rebecca occasionally makes home-made candy and works on her scrapbooks (she is woefully behind).`,
    ],
    isVerified: true,
  },
  {
    firstName: "A.R.",
    lastName: "Grosjean",
    email: "a.r.grosjean@hotmail.com",
    website: "https://argrosjeanauthor.wixsite.com/home",
    socialMedia: {
      facebook: "https://www.facebook.com/argrosjeanauthorwriter",
      instagram: "https://www.instagram.com/a.r.grosjeanauthor/",
    },
    umbrellaGenre: ["romance", "fantasy", "thriller", "scifi", "childrens"],
    subGenre: ["Paranormal Thriller"],
    bio: [
      `Explore where only the mind can reach! A.R. Grosjean is an author of Fantasy, Romance, Mystery, Paranormal, Thriller, Science Fiction, and beyond. With A.R. Grosjean (aka Amber), there's an adventure waiting to be explored. The sky is the limit--it's where Amber resides! View her books and find your next adventure!`,
      `Amber began her life's journey in a small farm community where she was bullied by her peers and family members. By the age of ten, she was ready to give up and attempted suicide. A year later, she discovered writing and the world she could create with her words. She was already a storyteller at heart. Since finding herself, she was able to turn her focus on healing and acceptance. She found where she belonged. Amber continues writing, creating new places to explore, and wants you to explore with her.`,
      `Amber lives in Fort Wayne with her husband of more than twenty-five years. She has released more than twenty books and continues to write. Her books have something different, making her unique in her own right. Visit her website for more information.`,
      `Amber believes that dreams can truly come true. Don't give up.`,
      `You can also sign up for her bi-weekly newsletter for updates, events, special news, and to learn about Amber and other writers as she supports other Indie Authors at subscribepage.io/p5o9p7 where you can find free gifts for signing up!`,
    ],
    isVerified: true,
  },
  {
    firstName: "Beronika",
    lastName: "Keres",
    email: "beronikakeres@gmail.com",
    website: "https://www.beronikakeres.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/AuthorBeronikaKeres",
      instagram: "https://www.instagram.com/beronikakeres/",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Thriller", "Vampire", "Dark Fantasy"],
    bio: [
      `Beronika Keres is the Canadian author of the dark fantasy thriller series, Cracked Coffins. She decided in the second grade that she wanted to be an author and has spent her life honing her craft and pursuing her dream. She can often be found chasing plot bunnies and writing books.`,
      `When she’s not writing, she enjoys spending time with her family, or listening to some gothic rock, punk, or metal while working on her newest spike and patch-covered project.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Rian F.",
    lastName: "Holes",
    email: "rianfholes@gmail.com",
    website: null,
    socialMedia: {
      instagram: "https://www.instagram.com/rianf.holes",
      twitter: "https://twitter.com/holes_f?t=PHUcyaLvpJ7DnsZeH_40zg&s=09",
      tiktok: "http://tiktok.com/@rianf.holes",
    },
    umbrellaGenre: ["thriller"],
    subGenre: ["Mystery", "Suspense", "Techno-Thriller"],
    bio: [
      `Rian F. Holes has started writing when he was seven years old by writing short stories about a teddy bear. Later as a teenager he wrote poetry, crime and science-fiction novels. While still being at school he started working as a freelance reporter for a local newspaper. He had studied HR and organizational man-agement and Catholic Theology. He is a for-mer business consultant and works as a teacher now. He had already published stories for children and articles about business management in international journals. Ice and Prey is his first internationally published novel for adults. He is married and father of two sons. Together with his family and a small dog he lives in a village in western Germany.`,
    ],
  },
  {
    firstName: "C.S.",
    lastName: "Smith",
    email: "c.s.smithauthor@gmail.com",
    website: "https://www.cssmithauthor.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/c.s.smithauthor/",
      facebook: "https://www.facebook.com/CSSmithAuthor19",
      tiktok: "https://www.tiktok.com/@c.s.smithauthor",
      goodreads: "https://www.goodreads.com/author/show/23127493.C_S_Smith",
      amazonBio: "https://www.amazon.com/author/c.s.smith",
      bookbub: "https://www.bookbub.com/authors/c-s-smith",
    },
    umbrellaGenre: ["romance"],
    subGenre: [
      "Romantic Suspense/Thriller",
      "Military Romance",
      "Action/Adventure Romance",
    ],
    bio: [
      `C.S. Smith writes steamy romantic suspense featuring former special operators. She admits to having a thing for alpha males. The bigger and badder, the harder they fall!`,
      `Her love of spine-tingling romance can be traced to her formative years in DC, surrounded by intrigue and handsome men in uniform—including the one she married.`,
      `A native New Englander who has spent over half her life in North Carolina, she’s an empty nester, leaving only her husband and "faux" Golden Retriever at her mercy.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Roy L.",
    lastName: "Pickering Jr.",
    email: "roylpickering@gmail.com",
    website: "http://roypickering.weebly.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/avaappelsawse/",
      facebook: "https://www.facebook.com/PatchesOfGrey/",
      tiktok: "https://www.tiktok.com/@mudhousebooks",
      twitter: "https://twitter.com/AuthorofPatches",
    },
    umbrellaGenre: ["childrens", "drama"],
    subGenre: ["Contemporary", "Literary", "African American"],
    bio: [
      `Roy Pickering is the author of the novels Patches of Grey and Matters of Convenience, a children's book entitled The Absolutely Amazing Adventures of Ava Appelsawse, and the novella Feeding the Squirrels. He is currently at work on his third novel. Anthologies that house Roy's shorter fiction include Proverbs for the People, Role Call, The Game: Short Stories About the Life, Prose to be Read Aloud and Forever Travels. He writes the blog A Line A Day which charts his diverse interests, and maintains Roy's Book Reviews, the YouTube channel where he shares his thoughts on books along with readings of children's books.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Susanne",
    lastName: "Perry",
    email: "susanneperryauthor@gmail.com",
    website: "https://susanneperrybooks.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/booksbysusanneperry",
    },
    umbrellaGenre: ["thriller"],
    subGenre: ["Mystery", "Short Stories"],
    bio: [
      `Susanne Perry is the author of the City Streets series of mysteries — Runaway, Veteran and Gutter Punk—set within the street community of the Pacific Northwest. Her short story, Prep Work was included in Riversong Books Best Short Stories of 2022.  A second short story entitled Karma and Santayana, was selected in 2023. Swan Song is set in Arizona and is her fourth novel.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Jae",
    lastName: "Greyn",
    email: "jaegreyn@gmail.com",
    website: "https://jaegreyn.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/jaegreyn",
    },
    umbrellaGenre: ["romance", "fantasy"],
    subGenre: ["LGBTQ Paranormal"],
    bio: [
      `Jae Greyn is the author of the Fire Ridge Pride Series. Born in the United States, Jae is an advocate for being good humans to animals and people. A consumer of coffee, chocolate, and romances. If you have any questions, you can check out https://jaegreyn.com`,
    ],
    isVerified: true,
  },
  {
    firstName: "Anne",
    lastName: "Daly",
    email: "careersforgirls@gmail.com",
    website: "https://annedaly.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/careersforgirls/",
      facebook: "https://www.facebook.com/Careers-for-Girls-107861405140547",
      amazonBio:
        "https://www.amazon.co.uk/stores/Anne-M-Daly/author/B09MKR1WZF?ref=ap_rdr&isDramIntegrated=true&shoppingPortalEnabled=true",
    },
    umbrellaGenre: ["childrens", "nonfiction"],
    subGenre: [
      "Informational",
      "Expository Descriptive",
      "Reference",
      "STEM",
      "Jobs",
    ],
    bio: [
      `Anne Daly has worked in management and in the STEM sector, in Ireland and America, building, repairing and troubleshooting computers. She has written for MsCareerGirl.com and BooksIrelandMagazine.com and the EU-funded ‘Gearing Roles’ project, and is a member of ALLi and Writing.ie. Anne is a mother of two teenagers and she credits them for inspiring in her a passion to help children understand life; this has become the driving force behind her books. Born in 1969 and raised on the north side of Dublin, Ireland, Anne now lives in the rural midlands of Ireland, in a little bungalow, with her husband, two children, three stray cats and a big loud dog. Find out more about Anne’s animal friends, and her books, at AnneDaly.com.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Brianna R.",
    lastName: "Shaffery",
    email: "orders@brswrites.com",
    website: "http://brswrites.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/brs_writes/",
      facebook: "https://www.facebook.com/BRSWritesOfficial",
      twitter: "https://twitter.com/brswrites",
      tiktok: "http://tiktok.com/@brswrites",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Gaslamp Fantasy", "High Fantasy", "Magical Realism"],
    bio: [
      `Brianna R. Shaffery is a fantasy and speculative fiction author known for her young adult fantasy trilogy, the Heirs of Tenebris. Always looking toward her next project, Brianna has also written several novellas of various genres that can be read on her website, BRSwrites.com.`,
      `Aside from her love of literature, Brianna can often be found engaged in some kind of craft or whipping up one of her favorite desserts. Living happily on the East Coast, Brianna enjoys making new memories with friends and family set to a background of whatever’s playing on the radio.`,
      `Follow along on her journey by following Brianna on social media or by signing up for her newsletter at BRSwrites.com/newsletter, which includes exclusive insights, writing updates, and bonus content from her books.`,
    ],
    isVerified: true,
  },
  {
    firstName: "K.",
    lastName: "Iwancio",
    email: "authorkiwancio@gmail.com",
    website: "http://www.kiwancio.com/",
    socialMedia: {
      instagram: "https://instagram.com/k.iwancio_writes",
      facebook: "https://facebook.com/pages/K-Iwancio-Writes",
      tiktok: "https://www.tiktok.com/@kiwancio_writes",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Romantic Comedy", "Paranormal Romance"],
    bio: [
      `Don’t let those cartoony covers fool you. Even though they’re full of Hallmark-y romcom goodness, finger those pages deeper to the smut within! K. Iwancio has been an interior designer, artist, teacher, and volunteer. She has visited far-off planets, been on movie sets, and even checked some things off her Bucket List. She lives in South Central Pennsylvania.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Amy",
    lastName: "Cocke",
    email: "admin@amycocke.com",
    website: "https://www.amycocke.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/authoramycocke/",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["High Fantasy"],
    bio: [
      `Amy has always been a writer, but after years of doing “practical” and “responsible” things, she decided it was time to see one of those stories in book form.`,
      `When she’s not writing or working her day job, she’s riding her horse, reading, or occasionally doing outdoorsy things.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Steffy",
    lastName: "Smith",
    email: "steffysmith@steffysmithbooks.com",
    website: "https://steffysmithbooks.com/",
    socialMedia: {
      instagram: "https://instagram.com/steffysmithbooks",
      facebook: "https://www.facebook.com/profile.php?id=100078881846211",
      tiktok: "http://www.tiktok.com/@steffysmithbooks",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Historical Romance"],
    bio: [
      `For years I have loved to curl up with a romance novel and escape to a different era of love. Stepping back into the ballroom during the Regency era, swept away on a journey through the Scottish Highlands or whisked off to a majestic castle in medieval England. My own fantasies have whirled around in my mind and it is in these novels I can express a story of my own and dreams of another time.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Michelle",
    lastName: "Matteson",
    email: "nightrosebud@aol.com",
    website: null,
    socialMedia: {
      instagram: "https://www.instagram.com/thosethatglowgold/",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["New Adult"],
    bio: [
      `Michelle Matteson is a new author residing in Central Florida, although she wouldn't turn down the lifestyle of a swamp witch with unlimited wifi and chocolate. She relishes being an unapologetic geek, loving the fantasy, horror, and sci-fi genres. It was always her dream to write a book, and hopefully, with time and plenty of pizza, she can continue crafting stories for many years to come.`,
    ],
  },
  {
    firstName: "Sara",
    lastName: "Kate",
    email: "sarakateauthor@gmail.com",
    website: "http://www.sarakateauthor.com/",
    socialMedia: {
      instagram: "https://instagram.com/sarakateauthor",
      tiktok: "http://www.tiktok.com/@sarakateauthor",
      facebook: "https://www.facebook.com/sarakateauthor",
      amazonBio: "https://www.amazon.com/author/sarakate",
      bookbub: "https://www.bookbub.com/authors/sara-kate",
    },
    umbrellaGenre: ["thriller"],
    subGenre: ["Crime Fiction", "Mystery", "Psychological Thriller"],
    bio: [
      `Sara Kate started her writing career as a scriptwriter for promotional videos and short films.`,
      `Years later, she wrote her first mystery novel. She writes crime fiction mysteries and psychological thrillers in her RV.`,
      `Aside from writing, she enjoys rollerblading, photography, painting, and anything thriller/mystery related.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Caroline",
    lastName: "Corvin",
    email: "caroline@carolinecorvin.com",
    website: "https://carolinecorvin.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/carolinecorvin/",
      facebook: "https://www.facebook.com/CarolineCorvinWrites",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Time Travel", "Contemporary", "Small Town", "Paranormal"],
    bio: [
      `Caroline Corvin is a writer of romantic fiction. Before publishing her first novel, Caroline had a career in education, from classroom teacher of lively little people, to principal of a large primary school. Mother of fur kids—dogs, cats and vertically challenged horses—she’s sometimes described as animal obsessed. But she’s made room in her life for her other magnificent obsessions - travel, genealogy, history, some stargazing and, of course, books.`,
      `Raised under the shadow of a volcano in provincial New Zealand, she now lives on the edge of Auckland, the City of Sails with stunning beaches and good coffee (and surrounded by more volcanoes, fortunately extinct).`,
      `Caroline didn’t set out to write romance, but her characters took control the moment she let them loose on the page, reminding her that finding happy ever afters are the reason she’s one of those people who sometimes reads the last page first—just to be safe.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Arleta",
    lastName: "Rae",
    email: "araebooks@yahoo.com",
    website: "https://araebooks.wixsite.com/arletarae",
    socialMedia: {
      instagram: "http://www.instagram.com/authorarletarae",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["New Adult Fantasy", "Paranormal Romance", "Portal Fantasy"],
    bio: [
      `Arleta is a New England native. She lives surrounded by beautiful rolling hills with her cat, Ubba, and her dog, Lily. Arleta's mind has always been wrapped in a wild fantasy world, whether its of her own creation or one she's reading. When she isn't writing, you can find her with a book, hiking, or with friends and a mocha latte in hand. She just received her MA in ecopsychology from Naropa University where she wrote a lengthy thesis on language and myth and nature. Her love of nature is woven into her fantasy stories.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Xyvah M.",
    lastName: "Okoye",
    email: "xmokoye@gmail.com",
    website: "http://www.xmokoye.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/xmokoye/",
      tiktok: "https://www.tiktok.com/@xmokoye",
    },
    umbrellaGenre: ["fantasy", "nonfiction"],
    subGenre: ["Epic Fantasy", "Poetry", "Christian Literature (non-fiction)"],
    bio: [
      `Xyvah M. Okoye is an epic fantasy author and believer.`,
      `When she isn’t tinkering with the mechanics of another story, she might be refuelling her magic in a pool, on the beach, or close to some other body of water. And at times like that, with her pointy ears twitching and her button nose buried in a book, if you look close enough, you just might see the shimmering veil around her… The veil between this world, and hers… Between what is, and what possibly could be.`,
      `To find out more, visit www.xmokoye.com`,
      `Follow her on social media: @xmokoye`,
    ],
  },
  {
    firstName: "MK",
    lastName: "Ahearn",
    email: "Mkahearn.books@gmail.com",
    website: "https://theoriginalmk.com/",
    socialMedia: {
      instagram: "http://www.instagram.com/mkahearn.books",
      tiktok: "https://www.tiktok.com/@mkbooks?_t=8gRyhOSDOyk&_r=1",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Fantasy Romance", "Epic Fantasy", "Anthologies"],
    bio: [
      `MK Ahearn grew up in Massachusetts as one of three sisters. She now lives in Maryland with her fiancé and their two cats. She received her bachelor of arts in international relations and is now completing a master of professional studies in homeland security. When not writing or studying she can be found planning her next travel adventure.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Julie",
    lastName: "Zantopoulos",
    email: "juliezeeauthor@gmail.com",
    website: "https://www.juliezee.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/according2jewls/",
      tiktok: "https://www.tiktok.com/@juliezeeauthor",
      twitter: "https://twitter.com/According2Jewls",
      amazonBio:
        "https://www.amazon.com/stores/Julie-Zantopoulos/author/B01BDUB8M4",
    },
    umbrellaGenre: ["romance"],
    subGenre: ["Fantasy Romance"],
    bio: [
      `Julie is the author of the adult fantasy romance In Ash series. `,
      `She grew up in the Philadelphia suburbs and now resides in Central Pennsylvania where she can view the mountains from her library window as she writes, which is perfect, because mountains have always held magic for her.`,
      `Julie graduated from Cabrini University with a degree in psychology. She prides herself on strong character building and relationship work as a result of her fascination with the connections people make. Her love of reading started before kindergarten, and she remains an avid reader, but writing is her true passion.`,
      `She's built a fantastic bookish community on YouTube where she discuss her love of writing and passion for reading with 10,000 followers. She is active on Instagram and Twitter, in love with TheStoryGraph (a Goodreads alternative), and mainly scrolls through TikTok instead of posting. Julie is quasi addicted to gummibears, loves tea (and has never tried coffee), and will drop everything for a fantastically ill produced SyFy channel movie. `,
      `She publishes under Julie Zantopoulos for her fantasy novels and hopes to publish contemporary romance through the name Julie Zee. The website is spelled as such for the ease of not typing a Greek last name. *you're welcome!`,
    ],
    isVerified: true,
  },
  {
    firstName: "Milagros S.",
    lastName: "Johnson",
    email: "milagrossjohnson@gmail.com",
    website: "https://www.milagrossjohnson.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/miljhnsn_author/",
    },
    umbrellaGenre: ["childrens"],
    subGenre: ["Financial Education"],
    bio: [
      `Milagros’ commitment and passion for financial literacy is demonstrated in her children’s picture book, Lolita’s Rainy Day. The story not only teaches the concept of money, from counting it to earning an allowance, it also inspires children (and their parents) to save money for a rainy day. The story is written in a way that is both humorous and educational.`,
      `She wrote the book hoping to plant a seed for the children to nurture so they can achieve financial independence and success in their adulthood.`,
      `Milagros has dedicated her career to her community, and her personal life to her loving and supportive family.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Meadoe",
    lastName: "Hora",
    email: "meadoehora@gmail.com",
    website: "https://www.meadoehora.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/meadoehorawrites/",
      instagram: "https://www.instagram.com/meadoehorawrites/",
      tiktok: "https://www.tiktok.com/@meadoehorawrites",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["YA Fantasy", "YA Urban Fantasy"],
    bio: [
      `Meadoe Hora is a writer, working mom, dog rescuer, and lover of beautiful words. She writes books for teens with strong female leads and classic mythology. She is the author of Ariadne’s Crown and the Furious Legacy series. In addition, her work has appeared in Chicken Soup for the Soul, Literary Mama, Sweatpants and Coffee, and other websites. You can find her at www.meadoehora.com. She lives in the US (WI) with her family, two spoiled basset hounds and a black lab who may or may not be a hellhound.`,
    ],
    isVerified: true,
  },
  {
    firstName: "C.K.",
    lastName: "Sorens",
    email: "cksorens@gmail.com",
    website: "http://www.cksorens.com/",
    socialMedia: {
      instagram: "https://www.instagram.com/ck_sorens/",
    },
    umbrellaGenre: ["fantasy"],
    subGenre: ["Urban Fantasy", "Speculative Fiction"],
    bio: [
      `C.K. Sorens is the USA Today Bestselling author of Eighteen Wishes, the Trimarked Series, and her short story collection, Vision of Misfortune. She is also a writing coach at Quill and Cup with a focus on mindset, craft, and creating a sustainable career.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Olivia",
    lastName: "Raymond",
    email: "author@OliviaRaymond.com",
    website: "https://www.oliviaraymond.com/",
    socialMedia: {
      facebook: "https://www.facebook.com/authoroliviaraymond/",
    },
    umbrellaGenre: ["thriller", "drama"],
    subGenre: ["Mystery"],
    bio: [
      `Olivia Raymond was born in the small town of Greensburg, Indiana, best known for the mulberry tree growing out of its courthouse tower. Olivia's family moved to Indianapolis when she was just seven years old, but by then, the small-town life had already taken root and made its lasting impression. Olivia had several careers before becoming a successful business entrepreneur. Her various life and career adventures provided her with many experiences that help shape her stories. She now resides in a small town with her family and sweet furry companion, Mr. Ralf, where she enjoys her time as a writer and volunteer for the arts in her community.`,
    ],
    isVerified: true,
  },
  {
    firstName: "Finley K.",
    lastName: "James",
    email: "finley.k.james29@gmail.com",
    website: "https://finleykjames.com/",
    umbrellaGenre: ["romance", "drama"],
    subGenre: ["Contemporary"],
    socialMedia: {
      instagram: "https://instagram.com/finleykjamesauthor",
      facebook: "https://facebook.com/finleykjamesauthor",
      twitter: null,
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: "https://threads.net/@finleykjamesauthor",
      bookbub: null,
    },
    bio: [
      "Hi! I’m Finley. I’m an 80-year-old woman in the body of a not-so-80-years-old woman. I write contemporary romance full of love, drama, and character growth. I live in the southern Midwest with my husband, our three kids, and our cats. I spend most of my time dreaming of the next project and word-vomiting onto pages only to delete them later. ",
    ],
    isVerified: true,
  },
  {
    firstName: "Jamie",
    lastName: "Payne",
    email: "jamie@biggledink.co.uk",
    website: "https://www.biggledink.co.uk/",
    umbrellaGenre: ["childrens"],
    subGenre: ["Picture Books", "Early Readers"],
    socialMedia: {
      instagram: "https://www.instagram.com/biggle.dink/",
      facebook: "https://www.facebook.com/biggledink",
      twitter: "https://twitter.com/biggledink",
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: null,
      bookbub: null,
    },
    bio: [
      "Biggle-Dink is a curious child who is fascinated by the seemingly ordinary world around them. With new discoveries and interests come new emotions and feelings. Join Biggle-Dink and their friends as we explore some of these new things together and discover how they might make us feel.",
      "Created by children's author Jamie Payne, Biggle-Dink is the title character of a collection of illustrated books that focus on different feelings and emotions that children can experience. The stories are written for younger children, with a broad targeted age range of 2 to 8 years old. They can be read to your little ones and also enjoyed independently by those older.",
    ],
    isVerified: true,
  },
  {
    firstName: "Dominique",
    lastName: "Davis",
    email: "contact@dominique-davis.com",
    website: "https://www.dominique-davis.com/",
    umbrellaGenre: ["romance"],
    subGenre: ["Contemporary", "New Adult"],
    socialMedia: {
      instagram: "https://instagram.com/ddaviswrites",
      facebook: null,
      twitter: "https://twitter.com/ddaviswrites",
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: null,
      bookbub: null,
    },
    bio: [
      "A 20-year-old writer who writes about pop culture and unhinged women falling in love (many of whom are sapphic).",
    ],
    isVerified: true,
  },
  {
    firstName: "S J",
    lastName: "Sparkle",
    email: "sjsparkle86@gmail.com",
    website: "https://www.stefansparkleauthor.com/",
    umbrellaGenre: ["romance"],
    subGenre: ["Regency Heartwarming"],
    socialMedia: {
      instagram: "http://instagram.com/sjsparkleauthor",
      facebook: null,
      twitter: null,
      tiktok: null,
      goodreads: null,
      mastodon: null,
      amazonBio: null,
      threads: "https://www.threads.net/@sjsparkleauthor",
      bookbub: null,
    },
    bio: [
      "S J Sparkle is true to his name, which was given to him when he got married. It's not a pseudonym it's a way of life! ",
      "He writes heartwarming cozy regency romance novels that are tastefully spicy, research heavy, and have just enough going on to keep you turning the page.",
      "When he's not writing he's with his wife and cats or being a sparkly presence on Threads.",
    ],
  },
  {
    firstName: "Melina",
    lastName: "Druga",
    email: "melinadruga@outlook.com",
    website: "http://www.melinadruga.com/",
    umbrellaGenre: ["romance", "historicalfiction", "nonfiction"],
    subGenre: ["Rock Star Fiction", "Women's Fiction", "History"],
    socialMedia: {
      instagram: "https://www.instagram.com/melinadruga/",
      facebook: "https://www.facebook.com/MelinaDruga",
      twitter: null,
      tiktok: null,
      goodreads: "https://www.goodreads.com/MelinaDruga",
      mastodon: null,
      amazonBio: "https://www.amazon.com/Melina-Druga/e/B00FSFCJOW",
      threads: null,
      bookbub: "https://www.bookbub.com/profile/melina-druga",
    },
    bio: [
      "Rumor has it that Melina Druga came out of her mother’s womb with a pen in her hand.  While we can neither confirm or deny this, you could say she was destined to become a writer.",
      "Melina was so young when she began writing that she can’t remember exactly when the urge began.  She does remember, however, her first novel – an historical fiction story about two sisters living in an Ohio canal town in the 1840s – that she wrote at age 10.",
      "Music keeps Melina sane, and it has gotten to the point that she cannot write without it.  It keeps her awake, alert, motivated and productive.  Music has even inspired her fiction.  And not just The Rock Star’s Wife series.  The My Chemical Romance song “Mama” was the inspiration for her historical fiction novel Angel of Mercy.",
      "Melina lives in the Midwest with her husband, daughter, black cat, books and CD collection.",
    ],
    isVerified: true,
  },
  {
    firstName: "Deborah",
    lastName: "Fox",
    email: "debmac730@gmail.com",
    website: null,
    umbrellaGenre: ["thriller", "horror"],
    subGenre: ["Mystery"],
    socialMedia: {
      instagram: "https://www.instagram.com/deborah9553/",
      facebook: "https://www.facebook.com/deborah.fox.127",
      twitter: "https://twitter.com/debmac730",
      tiktok: "https://www.tiktok.com/@deborah.fox5?_t=8idvTMKrMXp&_r=1",
      goodreads: "https://www.goodreads.com/author/show/34223403.D_E_Fox",
      mastodon: null,
      amazonBio:
        "https://www.amazon.co.uk/stores/D%20E%20Fox/author/B0C4G3GQ6G",
      threads: "https://www.threads.net/@deborah9553",
      bookbub: null,
    },
    bio: [
      "I am 50 years old and live in Doncaster a city in the north of England. When not writing I work for a large electrical distribution company in a busy returns department. My hobbies include gardening, walking, dogs, cinema / theatre and promoting my book Second Hand Rose. This is my first book and it was written and inspired by my dog Jake who sadly passed away so I made him one of the main characters of the story which I then wrote to help with the grieving process.",
    ],
  },
];
