export const AwaitingAuthors = [
  {
    firstName: "Test",
    lastName: "Eight",
    email: "test8@test.com",
    website: "https://www.test8.com/",
    umbrellaGenre: ["childrens", "nonfiction"],
    subGenre: ["Adventure", "STEM"],
    instagram: "https://www.instagram.com/test8/",
    facebook: "https://www.facebook.com/test8",
    twitter: null,
    threads: "https://www.threads.net/@test8",
    tiktok: "https://www.tiktok.com/@test8",
    goodreads: "https://www.goodreads.com/author/show/16568357.test8",
    amazonBio: "https://www.amazon.com/stores/author/test8",
    bio: "test 8 \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "Nine",
    email: "test9@test.com",
    website: "https://www.test9.com/",
    umbrellaGenre: ["thriller", "nonfiction"],
    subGenre: ["Mystery", "STEM"],
    instagram: "https://www.instagram.com/test9/",
    facebook: "https://www.facebook.com/test9",
    twitter: null,
    threads: "https://www.threads.net/@test9",
    tiktok: "https://www.tiktok.com/@test9",
    goodreads: "https://www.goodreads.com/author/show/16568357.test9",
    amazonBio: "https://www.amazon.com/stores/author/test9",
    bio: "test 9 \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "Ten",
    email: "test10@test.com",
    website: "https://www.test10.com/",
    umbrellaGenre: ["thriller", "horror"],
    subGenre: ["Mystery", "Slasher"],
    instagram: "https://www.instagram.com/test10/",
    facebook: "https://www.facebook.com/test10",
    twitter: null,
    threads: "https://www.threads.net/@test10",
    tiktok: "https://www.tiktok.com/@test10",
    goodreads: "https://www.goodreads.com/author/show/16568357.test10",
    amazonBio: "https://www.amazon.com/stores/author/test10",
    bio: "test 10 \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "Eleven",
    email: "test11@test.com",
    website: "https://www.test11.com/",
    umbrellaGenre: ["thriller", "horror"],
    subGenre: ["Mystery", "Slasher"],
    instagram: "https://www.instagram.com/test11/",
    facebook: "https://www.facebook.com/test11",
    twitter: null,
    threads: "https://www.threads.net/@test11",
    tiktok: "https://www.tiktok.com/@test11",
    goodreads: "https://www.goodreads.com/author/show/16568357.test11",
    amazonBio: "https://www.amazon.com/stores/author/test11",
    bio: "test 11 \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "Twelve",
    email: "test12@test.com",
    website: "https://www.test12.com/",
    umbrellaGenre: ["scifi", "horror"],
    subGenre: ["Aliens", "Slasher"],
    instagram: "https://www.instagram.com/test12/",
    facebook: "https://www.facebook.com/test12",
    twitter: null,
    threads: "https://www.threads.net/@test12",
    tiktok: "https://www.tiktok.com/@test12",
    goodreads: "https://www.goodreads.com/author/show/16568357.test12",
    amazonBio: "https://www.amazon.com/stores/author/test12",
    bio: "test 12 \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "Thirteen",
    email: "test13@test.com",
    website: "https://www.test13.com/",
    umbrellaGenre: ["comedy", "nonfiction"],
    subGenre: ["Slapstick", "Coding"],
    instagram: "https://www.instagram.com/test13/",
    facebook: "https://www.facebook.com/test13",
    twitter: null,
    threads: "https://www.threads.net/@test13",
    tiktok: "https://www.tiktok.com/@test13",
    goodreads: "https://www.goodreads.com/author/show/16568357.test13",
    amazonBio: "https://www.amazon.com/stores/author/test13",
    bio: "test 13 \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "Fourteen",
    email: "test14@test.com",
    website: "https://www.test14.com/",
    umbrellaGenre: ["dystopian", "western"],
    subGenre: ["WW3", "Wild West"],
    instagram: "https://www.instagram.com/test14/",
    facebook: "https://www.facebook.com/test14",
    twitter: null,
    threads: "https://www.threads.net/@test14",
    tiktok: "https://www.tiktok.com/@test14",
    goodreads: "https://www.goodreads.com/author/show/16568357.test14",
    amazonBio: "https://www.amazon.com/stores/author/test14",
    bio: "test 14 \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "I",
    email: "testI@test.com",
    website: "https://www.testI.com/",
    umbrellaGenre: ["comedy", "nonfiction"],
    subGenre: ["Politics", "Coding"],
    instagram: "https://www.instagram.com/testI/",
    facebook: "https://www.facebook.com/testI",
    twitter: null,
    threads: "https://www.threads.net/@testI",
    tiktok: "https://www.tiktok.com/@testI",
    goodreads: "https://www.goodreads.com/author/show/16568357.testI",
    amazonBio: "https://www.amazon.com/stores/author/testI",
    bio: "test I \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "II",
    email: "testII@test.com",
    website: "https://www.testII.com/",
    umbrellaGenre: ["thriller"],
    subGenre: ["Spy", "Action"],
    instagram: "https://www.instagram.com/testII/",
    facebook: "https://www.facebook.com/testII",
    twitter: null,
    threads: "https://www.threads.net/@testII",
    tiktok: "https://www.tiktok.com/@testII",
    goodreads: "https://www.goodreads.com/author/show/16568357.testII",
    amazonBio: "https://www.amazon.com/stores/author/testII",
    bio: "test II \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "III",
    email: "testIII@test.com",
    website: "https://www.testIII.com/",
    umbrellaGenre: ["thriller"],
    subGenre: ["Spy", "Action"],
    instagram: "https://www.instagram.com/testIII/",
    facebook: "https://www.facebook.com/testIII",
    twitter: null,
    threads: "https://www.threads.net/@testIII",
    tiktok: "https://www.tiktok.com/@testIII",
    goodreads: "https://www.goodreads.com/author/show/16568357.testIII",
    amazonBio: "https://www.amazon.com/stores/author/testIII",
    bio: "test III \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "IV",
    email: "testIV@test.com",
    website: "https://www.testIV.com/",
    umbrellaGenre: ["thriller", "romance"],
    subGenre: ["Spy", "Action", "Kissy Stuff"],
    instagram: "https://www.instagram.com/testIV/",
    facebook: "https://www.facebook.com/testIV",
    twitter: null,
    threads: "https://www.threads.net/@testIV",
    tiktok: "https://www.tiktok.com/@testIV",
    goodreads: "https://www.goodreads.com/author/show/16568357.testIV",
    amazonBio: "https://www.amazon.com/stores/author/testIV",
    bio: "test IV \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "V",
    email: "testV@test.com",
    website: "https://www.testV.com/",
    umbrellaGenre: ["comedy"],
    subGenre: ["Funny Stuff"],
    instagram: "https://www.instagram.com/testV/",
    facebook: "https://www.facebook.com/testV",
    twitter: null,
    threads: "https://www.threads.net/@testV",
    tiktok: "https://www.tiktok.com/@testV",
    goodreads: "https://www.goodreads.com/author/show/16568357.testV",
    amazonBio: "https://www.amazon.com/stores/author/testV",
    bio: "test V \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "VI",
    email: "testVI@test.com",
    website: "https://www.testVI.com/",
    umbrellaGenre: ["scifi"],
    subGenre: ["Alien Stuff"],
    instagram: "https://www.instagram.com/testVI/",
    facebook: "https://www.facebook.com/testVI",
    twitter: null,
    threads: "https://www.threads.net/@testVI",
    tiktok: "https://www.tiktok.com/@testVI",
    goodreads: "https://www.goodreads.com/author/show/16568357.testVI",
    amazonBio: "https://www.amazon.com/stores/author/testVI",
    bio: "test VI \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "VII",
    email: "testVII@test.com",
    website: "https://www.testVII.com/",
    umbrellaGenre: ["comedy"],
    subGenre: ["Funny Stuff"],
    instagram: "https://www.instagram.com/testVII/",
    facebook: "https://www.facebook.com/testVII",
    twitter: null,
    threads: "https://www.threads.net/@testVII",
    tiktok: "https://www.tiktok.com/@testVII",
    goodreads: "https://www.goodreads.com/author/show/16568357.testVII",
    amazonBio: "https://www.amazon.com/stores/author/testVII",
    bio: "test VII \nparagraph 2\nparagraph 3\nparagraph 4",
  },
  {
    firstName: "Test",
    lastName: "VIII",
    email: "testVIII@test.com",
    website: "https://www.testVIII.com/",
    umbrellaGenre: ["horror"],
    subGenre: ["Scary Stuff"],
    instagram: "https://www.instagram.com/testVIII/",
    facebook: "https://www.facebook.com/testVIII",
    twitter: null,
    threads: "https://www.threads.net/@testVIII",
    tiktok: "https://www.tiktok.com/@testVIII",
    goodreads: "https://www.goodreads.com/author/show/16568357.testVIII",
    amazonBio: "https://www.amazon.com/stores/author/testVIII",
    bio: "test VIII \nparagraph 2\nparagraph 3\nparagraph 4",
  },
];